# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chart_store.proto

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chart_store.proto',
  package='datacommons.proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x63hart_store.proto\x12\x11\x64\x61tacommons.proto\"\xae\x01\n\rObsTimeSeries\x12\x36\n\x03val\x18\x01 \x03(\x0b\x32).datacommons.proto.ObsTimeSeries.ValEntry\x12\x0c\n\x04unit\x18\x02 \x01(\t\x12\x12\n\nplace_name\x18\x03 \x01(\t\x12\x17\n\x0fis_dc_aggregate\x18\x04 \x01(\x08\x1a*\n\x08ValEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"\xf6\x01\n\rObsCollection\x12\x36\n\x03val\x18\x01 \x03(\x0b\x32).datacommons.proto.ObsCollection.ValEntry\x12\x0c\n\x04unit\x18\x02 \x01(\t\x12\x17\n\x0fis_dc_aggregate\x18\x03 \x01(\x08\x1a\x30\n\x07ObsInfo\x12\x12\n\nplace_name\x18\x01 \x01(\t\x12\x11\n\tobs_value\x18\x02 \x01(\x01\x1aT\n\x08ValEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x37\n\x05value\x18\x02 \x01(\x0b\x32(.datacommons.proto.ObsCollection.ObsInfo:\x02\x38\x01\"\x8c\x01\n\nChartStore\x12;\n\x0fobs_time_series\x18\x01 \x01(\x0b\x32 .datacommons.proto.ObsTimeSeriesH\x00\x12:\n\x0eobs_collection\x18\x02 \x01(\x0b\x32 .datacommons.proto.ObsCollectionH\x00\x42\x05\n\x03val')
)




_OBSTIMESERIES_VALENTRY = _descriptor.Descriptor(
  name='ValEntry',
  full_name='datacommons.proto.ObsTimeSeries.ValEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='datacommons.proto.ObsTimeSeries.ValEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='datacommons.proto.ObsTimeSeries.ValEntry.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=215,
)

_OBSTIMESERIES = _descriptor.Descriptor(
  name='ObsTimeSeries',
  full_name='datacommons.proto.ObsTimeSeries',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='datacommons.proto.ObsTimeSeries.val', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unit', full_name='datacommons.proto.ObsTimeSeries.unit', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='place_name', full_name='datacommons.proto.ObsTimeSeries.place_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_dc_aggregate', full_name='datacommons.proto.ObsTimeSeries.is_dc_aggregate', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_OBSTIMESERIES_VALENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=215,
)


_OBSCOLLECTION_OBSINFO = _descriptor.Descriptor(
  name='ObsInfo',
  full_name='datacommons.proto.ObsCollection.ObsInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='place_name', full_name='datacommons.proto.ObsCollection.ObsInfo.place_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='obs_value', full_name='datacommons.proto.ObsCollection.ObsInfo.obs_value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=378,
)

_OBSCOLLECTION_VALENTRY = _descriptor.Descriptor(
  name='ValEntry',
  full_name='datacommons.proto.ObsCollection.ValEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='datacommons.proto.ObsCollection.ValEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='datacommons.proto.ObsCollection.ValEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=464,
)

_OBSCOLLECTION = _descriptor.Descriptor(
  name='ObsCollection',
  full_name='datacommons.proto.ObsCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='datacommons.proto.ObsCollection.val', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unit', full_name='datacommons.proto.ObsCollection.unit', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_dc_aggregate', full_name='datacommons.proto.ObsCollection.is_dc_aggregate', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_OBSCOLLECTION_OBSINFO, _OBSCOLLECTION_VALENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=464,
)


_CHARTSTORE = _descriptor.Descriptor(
  name='ChartStore',
  full_name='datacommons.proto.ChartStore',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='obs_time_series', full_name='datacommons.proto.ChartStore.obs_time_series', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='obs_collection', full_name='datacommons.proto.ChartStore.obs_collection', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='val', full_name='datacommons.proto.ChartStore.val',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=467,
  serialized_end=607,
)

_OBSTIMESERIES_VALENTRY.containing_type = _OBSTIMESERIES
_OBSTIMESERIES.fields_by_name['val'].message_type = _OBSTIMESERIES_VALENTRY
_OBSCOLLECTION_OBSINFO.containing_type = _OBSCOLLECTION
_OBSCOLLECTION_VALENTRY.fields_by_name['value'].message_type = _OBSCOLLECTION_OBSINFO
_OBSCOLLECTION_VALENTRY.containing_type = _OBSCOLLECTION
_OBSCOLLECTION.fields_by_name['val'].message_type = _OBSCOLLECTION_VALENTRY
_CHARTSTORE.fields_by_name['obs_time_series'].message_type = _OBSTIMESERIES
_CHARTSTORE.fields_by_name['obs_collection'].message_type = _OBSCOLLECTION
_CHARTSTORE.oneofs_by_name['val'].fields.append(
  _CHARTSTORE.fields_by_name['obs_time_series'])
_CHARTSTORE.fields_by_name['obs_time_series'].containing_oneof = _CHARTSTORE.oneofs_by_name['val']
_CHARTSTORE.oneofs_by_name['val'].fields.append(
  _CHARTSTORE.fields_by_name['obs_collection'])
_CHARTSTORE.fields_by_name['obs_collection'].containing_oneof = _CHARTSTORE.oneofs_by_name['val']
DESCRIPTOR.message_types_by_name['ObsTimeSeries'] = _OBSTIMESERIES
DESCRIPTOR.message_types_by_name['ObsCollection'] = _OBSCOLLECTION
DESCRIPTOR.message_types_by_name['ChartStore'] = _CHARTSTORE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ObsTimeSeries = _reflection.GeneratedProtocolMessageType('ObsTimeSeries', (_message.Message,), dict(

  ValEntry = _reflection.GeneratedProtocolMessageType('ValEntry', (_message.Message,), dict(
    DESCRIPTOR = _OBSTIMESERIES_VALENTRY,
    __module__ = 'chart_store_pb2'
    # @@protoc_insertion_point(class_scope:datacommons.proto.ObsTimeSeries.ValEntry)
    ))
  ,
  DESCRIPTOR = _OBSTIMESERIES,
  __module__ = 'chart_store_pb2'
  # @@protoc_insertion_point(class_scope:datacommons.proto.ObsTimeSeries)
  ))
_sym_db.RegisterMessage(ObsTimeSeries)
_sym_db.RegisterMessage(ObsTimeSeries.ValEntry)

ObsCollection = _reflection.GeneratedProtocolMessageType('ObsCollection', (_message.Message,), dict(

  ObsInfo = _reflection.GeneratedProtocolMessageType('ObsInfo', (_message.Message,), dict(
    DESCRIPTOR = _OBSCOLLECTION_OBSINFO,
    __module__ = 'chart_store_pb2'
    # @@protoc_insertion_point(class_scope:datacommons.proto.ObsCollection.ObsInfo)
    ))
  ,

  ValEntry = _reflection.GeneratedProtocolMessageType('ValEntry', (_message.Message,), dict(
    DESCRIPTOR = _OBSCOLLECTION_VALENTRY,
    __module__ = 'chart_store_pb2'
    # @@protoc_insertion_point(class_scope:datacommons.proto.ObsCollection.ValEntry)
    ))
  ,
  DESCRIPTOR = _OBSCOLLECTION,
  __module__ = 'chart_store_pb2'
  # @@protoc_insertion_point(class_scope:datacommons.proto.ObsCollection)
  ))
_sym_db.RegisterMessage(ObsCollection)
_sym_db.RegisterMessage(ObsCollection.ObsInfo)
_sym_db.RegisterMessage(ObsCollection.ValEntry)

ChartStore = _reflection.GeneratedProtocolMessageType('ChartStore', (_message.Message,), dict(
  DESCRIPTOR = _CHARTSTORE,
  __module__ = 'chart_store_pb2'
  # @@protoc_insertion_point(class_scope:datacommons.proto.ChartStore)
  ))
_sym_db.RegisterMessage(ChartStore)


_OBSTIMESERIES_VALENTRY._options = None
_OBSCOLLECTION_VALENTRY._options = None
# @@protoc_insertion_point(module_scope)
