# Run Python tests, lint, etc.
steps:

- name: python:3.7
  entrypoint: python3
  args: ["-m" , "pip" , "install" , "-t" , "." , "-r" , "requirements.txt"]

- name: python:3.7
  entrypoint: python3
  args: ["-m", "pytest"]

- name: python:3.7
  entrypoint: python3
  dir: 'tools/pv_tree_generator'
  args: ["-m" , "pip" , "install" , "-t" , "." , "-r" , "requirements.txt"]

- name: python:3.7
  entrypoint: python3
  dir: 'tools/pv_tree_generator'
  args: ["-m", "pytest"]

# TODO: Add Python linter, format checker, and any other useful code health tools.