# Run Python tests, lint, etc.
steps:

- id: flask_test
  name: python:3.7-slim
  entrypoint: /bin/sh
  args:
  - -c
  - 'cd server && pip install -r requirements.txt && python -m pytest'

- id: pv_tree_generator
  name: python:3.7-slim
  entrypoint: /bin/sh
  args:
  - -c
  - 'cd tools/pv_tree_generator && pip install -r requirements.txt && python -m pytest'

# TODO: Add Python linter, format checker, and any other useful code health tools.