# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## This file specifies the topic page config for poverty in USA

metadata {
  topic_id: "playground"
  topic_name: "TechSoup Topic Page Playground"
  place_group {
    parent_place: "country/USA"
    place_type: "State"
  }
  place_group {
    parent_place: "country/USA"
    place_type: "County"
  }
  contained_place_types {
    key: "State"
    value: "County"
  }
  contained_place_types {
    key: "County"
    value: "CensusTract"
  }
}

categories {
  title: "Test"
  blocks {
    title: "Using markdown in descriptions"
    columns {
      tiles {
        type: DESCRIPTION
        description: "# This is a test of markdown.\nThis is a description. Does *Markdown* work?\n* Yes or\n* No\n\n What about a [link](https://www.techsoup.org)?"
      }
    }
    
  }


  blocks {
    title: "Excess food generation from restaurants"
    
    columns {
      tiles {
        type: HIGHLIGHT
        description: "Excess food generation from restaurants in ${placeName}"
        stat_var_key: "restaurant_excessfoodgeneration"
      }
    }

    columns {
      tiles {
        type: MAP
        stat_var_key: "restaurant_excessfoodgeneration"
        title: "Excess food generation from restaurants by county"
      }
    }
  }

  stat_var_spec {
    key: "household_median_income"
    value {
      stat_var: "Median_Income_Household"
      name: "Household Median Income"
    }
  }

  stat_var_spec {
    key: "restaurant_excessfoodgeneration"
    value {
      stat_var: "dc/963qtn2mpnbs"
      name: "Excess food generated by full service restaurants"
      scaling: 1.38
      unit: "Tons"
    }
  }
}
