/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Wall of links to example charts for the visualization tools
 */

import React from "react";

import { LinkChips } from "../../../components/content/link_chips";
import { Link } from "../../../components/elements/link_chip";
import { intl } from "../../../i18n/i18n";
import {
  toolMessages,
  VisToolExampleChartMessages,
} from "../../../i18n/i18n_tool_messages";

interface ChartLinkChipsProps {
  toolType: "map" | "scatter" | "timeline";
}

declare global {
  interface Window {
    chartLinksConfig?: ToolExampleLink[];
  }
}

/**
 * Config interface corresponding to the JSON for the vis tool examples
 */
interface ToolExampleLink {
  // The id of the example (if not provided, this will be autogenerated)
  id?: string;
  // An optional title. This will be the text displayed in the link chip.
  // Takes precedence over titleMessageId if both are provided.
  title?: string;
  // An optional i18n message ID. If provided (and no title is present),
  // this will be run through the i18n object and translated.
  titleMessageId?: string;
  // the URL of the example
  url: string;
}

/**
 * Gets the set of link chips for the correct tool from the vis tool config
 */
function getLinkChips(): Link[] {
  const config = globalThis.chartLinksConfig;

  if (!config || !Array.isArray(config)) {
    return [];
  }

  const links: Link[] = [];
  let generatedId = 0;

  for (const item of config) {
    let finalTitle = item.title;

    // If no hardcoded title is provided, fall back to the translated message ID
    if (
      !finalTitle &&
      item.titleMessageId &&
      VisToolExampleChartMessages[item.titleMessageId]
    ) {
      finalTitle = intl.formatMessage(
        VisToolExampleChartMessages[item.titleMessageId]
      );
    }

    // If we still don't have a title (neither was provided, or translation failed), skip entirely
    if (!finalTitle) {
      continue;
    }

    links.push({
      id: item.id || `example-link-${generatedId++}`,
      title: finalTitle,
      url: item.url,
    });
  }

  return links;
}

export function ChartLinkChips(props: ChartLinkChipsProps): JSX.Element {
  return (
    <LinkChips
      variant="flat"
      header={intl.formatMessage(toolMessages.ExamplesHeader)}
      headerComponent="h4"
      section={`${props.toolType}_tool_example_charts`}
      linkChips={getLinkChips()}
      chipTextSize="sm"
    />
  );
}
