# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Helm config
project: "datcom-feedingamerica"
cluster_prefix: "website"

namespace:
  name: "website"

website:
  image:
    project: "datcom-ci"
    tag:
  githash:
  flaskEnv: feedingamerica
  replicas: 4

  redis:
    enabled: true
    configFile: |
      {
        "us-central1": {
          "host": "10.130.171.245",
          "port": "6379"
        }
      }

mixer:
  hostProject:
  serviceName:
  useTMCFCSVData: true
  tmcfCSVBucket: "datcom-feedingamerica-resources"
  tmcfCSVFolder: "food"

serviceAccount:
  name: website-ksa

nl:
  enabled: false

serviceGroups:
  recon: null
  observation:
    replicas: 4
  node:
    replicas: 4
  svg:
    replicas: 2
  default:
    replicas: 2

memdbJSON: |
  {
    "importName": "Feeding America",
    "provenanceUrl": "https://www.feedingamerica.org/",
    "dataDownloadUrl": "https://www.feedingamerica.org/",
    "rootSvg": "g/Feeding_America",
    "statVarGroups": {
      "g/Feeding_America": {
        "childStatVarGroups": [
          {
            "id": "g/Child_FoodInsecure",
            "specializedEntity": "Food Insecure Children"
          },
          {
            "id": "g/Person_FoodInsecure",
            "specializedEntity": "Food Insecure People"
          }
        ],
        "childStatVars": [
          {
            "id": "Annual_FoodBudgetShortfall",
            "searchNames": ["Annual Food Budget Shortfall"],
            "displayName": "Annual Food Budget Shortfall"
          },
          {
            "id": "Mean_MealCost_Person_FoodSecure",
            "searchNames": ["Food Secure Person Mean Meal Cost"],
            "displayName": "Average Meal Cost for Food Secure Persons"
          }
        ]
      },
      "g/Child_FoodInsecure": {
        "childStatVarGroups": [
          {
            "id": "g/Child_FoodInsecure_ChildNutritionBenefits",
            "specializedEntity": "Child Nutrition Benefits"
          }
        ],
        "childStatVars": [
          {
            "id": "Count_Child_FoodInsecure",
            "searchNames": ["Count of Food Insecure Child"],
            "displayName": "Population"
          }
        ]
      },
      "g/Child_FoodInsecure_ChildNutritionBenefits": {
        "childStatVars": [
          {
            "id": "Count_Child_FoodInsecure_EligibleForManyChildNutritionBenefits",
            "searchNames": [
              "Count of Child Food Insecure Eligible for Many Child Nutrition Benefits"
            ],
            "displayName": "Eligible"
          },
          {
            "id": "Count_Child_FoodInsecure_IneligibleForChildNutritionBenefits",
            "searchNames": [
              "Count of Child Food Insecure Ineligible for Many Child Nutrition Benefits"
            ],
            "displayName": "Ineligible"
          }
        ]
      },
      "g/Person_FoodInsecure": {
        "childStatVarGroups": [
          {
            "id": "g/Person_FoodInsecure_FederalBenefits",
            "specializedEntity": "Federal Benefits"
          }
        ],
        "childStatVars": [
          {
            "id": "Count_Person_FoodInsecure",
            "searchNames": ["Count of Person Food Insecure"],
            "displayName": "Population"
          }
        ]
      },
      "g/Person_FoodInsecure_FederalBenefits": {
        "childStatVars": [
          {
            "id": "Count_Person_FoodInsecure_EligibleForAllFederalBenefits",
            "searchNames": [
              "Count of Person with Food Insecure Eligible for All Federal Benefits"
            ],
            "displayName": "Eligible for All Federal Benefits"
          },
          {
            "id": "Count_Person_FoodInsecure_EligibleForSomeFederalBenefits",
            "searchNames": [
              "Count of Person with Food Insecure Eligible for Some Federal Benefits"
            ],
            "displayName": "Eligible for Some Federal Benefits"
          },
          {
            "id": "Count_Person_FoodInsecure_IneligibleForFederalBenefits",
            "searchNames": [
              "Count of Person with Food Insecure Ineligible for Federal Benefits"
            ],
            "displayName": "Ineligible for Federal Benefits"
          }
        ]
      }
    }
  }
