# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Helm config

project: datcom-karnataka

cluster_prefix: "website"

namespace:
  name: "website"

website:
  image:
    project: "datcom-ci"
    tag:
  flaskEnv: worldbank
  replicas: 3

mixer:
  useBaseBigtable: false
  useBranchBigtable: false
  useCustomBigtable: true
  # TODO: update to https://api.datacommons.org and change the mixer_api_key
  # in Cloud Secret Manager before launch.
  remoteMixerDomain: https://autopush.api.datacommons.org

ingress:
  enabled: true
  ipName: website-ip
  certName: website-certificate

serviceAccount:
  name: website-ksa

serviceGroups:
  recon: null
  svg: null
  observation: null
  node: null
  default:
    replicas: 3
    cacheSVG: true # No svg service, this needs to use search
    resources:
      memoryRequest: "8G"
      memoryLimit: "8G"
nl:
  enabled: false

kgStoreConfig:
  customBigtableInfo: |
    project:
    instance: dc-graph
    tables:
      -

svg:
  blocklistFile: ["dc/g/Uncategorized", "oecd/g/OECD"]
