# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## This file specifies the disaster dashboard config for Earth.

metadata {
  topic_id: "disaster_dashboard"
  topic_name: "Disaster Dashboard"
  place_dcid: "Earth"
  contained_place_types {
    key: "Planet"
    value: "Country"
  }
  event_type_spec {
    key: 'earthquake'
    value: {
      id: "earthquake"
      name: "Earthquake"
      event_type_dcids: "EarthquakeEvent"
    }
  }
  event_type_spec {
    key: 'flood'
    value: {
      id: "flood"
      name: "Flood"
      event_type_dcids: "FloodEvent"
    }
  }
  event_type_spec {
    key: 'fire'
    value: {
      id: "fire"
      name: "Fire"
      event_type_dcids: "WildlandFireEvent"
      event_type_dcids: "WildfireEvent"
    }
  }
  event_type_spec {
    key: 'storm'
    value: {
      id: "storm"
      name: "Storm"
      event_type_dcids: "CycloneEvent"
      event_type_dcids: "TornadoEvent"
      event_type_dcids: "HurricaneEvent"
      event_type_dcids: "HurricaneTyphoonEvent"
    }
  }
  event_type_spec {
    key: 'drought'
    value: {
      id: "drought"
      name: "Drought"
      event_type_dcids: "DroughtEvent"
    }
  }
}

categories {
  blocks {
    columns {
      tiles: {
        type: DISASTER_EVENT_MAP
        disaster_event_map_tile_spec: {
          event_type_keys: 'earthquake'
          event_type_keys: 'flood'
          event_type_keys: 'fire'
          event_type_keys: 'storm'
          event_type_keys: 'drought'
        }
      }
    }
  }
}