# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## This file specifies the topic page config for poverty in USA

metadata {
  topic_id: 'poverty'
  topic_name: 'Poverty'
  place_dcid: 'country/IND'
  contained_place_types {
    key: 'Country'
    value: 'State'
  }
}

categories {
  title: "Individual poverty"
  blocks {
    columns {
      tiles {
        type: HIGHLIGHT
        description: "of Indians lived under the poverty line (${date})"
        stat_var_key: "poverty_rate"
      }
    }
    columns {
      tiles {
        type: LINE
        title: "Poverty rate in ${placeName}"
        stat_var_key: "poverty_rate"
      }
    }
  }

  blocks {
    title: "Poverty across states"
    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "poverty_rate"
      }
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
          highest_title: "Most ${statVar}"
          lowest_title: "Fewest ${statVar}"
        }
        stat_var_key: "poverty_count"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "Poverty rate across states (${date})"
        stat_var_key: "poverty_rate"
      }
    }
  }

  blocks {
    title: "Wages"
    description: "Mean monthly wages"
    columns {
      tiles {
        title: "Mean monthly wages in ${placeName}"
        type: LINE
        stat_var_key: "monthly_wages"
      }
    }
    columns {
      tiles {
        type: HIGHLIGHT
        description: "Mean monthly wages across India (${date})"
        stat_var_key: "monthly_wages"
      }
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "monthly_wages"
      }
    }
  }

  blocks {
    title: "Urban vs. Rural"
    description: "Percentage of those below poverty who live in urban vs. rural areas"
    columns {
      tiles: {
        title: "Urban vs. Rural among those below poverty in ${placeName}"
        type: LINE
        stat_var_key: "poverty_rate_urban"
        stat_var_key: "poverty_rate_rural"
      }
    }
    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
        }
        stat_var_key: "poverty_rate_urban"
        stat_var_key: "poverty_rate_rural"
      }
    }
  }

  blocks {
    title: "Literacy and poverty"
    columns {
      tiles {
        title: "Poverty rate vs. Illiteracy rate"
        type: SCATTER
        stat_var_key: "poverty_rate"
        stat_var_key: "illiteracy_rate"
      }
    }
    columns {
      tiles {
        title: "Poverty rate vs. Illiteracy rate"
        type: BIVARIATE
        stat_var_key: "poverty_rate"
        stat_var_key: "illiteracy_rate"
      }
    }
  }

  blocks {
    title: "Temperature rise and poverty"
    columns {
      tiles {
        title: "Max temp relative to 2015 (RCP 8.5, SSP 5) vs. Poverty rate"
        type: SCATTER
        stat_var_key: "max_temp_diff"
        stat_var_key: "poverty_rate"
      }
    }
    columns {
      tiles {
        title: "Max temp relative to 2015 (RCP 8.5, SSP 5) vs. Poverty rate"
        type: BIVARIATE
        stat_var_key: "max_temp_diff"
        stat_var_key: "poverty_rate"
      }
    }
  }

  stat_var_spec {
    key: "poverty_rate"
    value {
      stat_var: "Count_Person_BelowPovertyLevelInThePast12Months_AsFractionOf_Count_Person"
      unit: "%"
      name: "Poverty rate"
    }
  }
  stat_var_spec {
    key: "poverty_count"
    value {
      stat_var: "Count_Person_BelowPovertyLevelInThePast12Months"
      name: "people in poverty"
    }
  }
  stat_var_spec {
    key: "monthly_wages"
    value {
      stat_var: "Mean_WagesMonthly_Worker"
      name: "Mean monthly wages"
      unit: "₹"
    }
  }
  stat_var_spec {
    key: "poverty_rate_urban"
    value {
      stat_var: "Count_Person_Urban_BelowPovertyLevelInThePast12Months"
      denom: "Count_Person_BelowPovertyLevelInThePast12Months"
      unit: "%"
      scaling: 100
      name: "Share of poor in urban areas"
    }
  }
  stat_var_spec {
    key: "poverty_rate_rural"
    value {
      stat_var: "Count_Person_Rural_BelowPovertyLevelInThePast12Months"
      denom: "Count_Person_BelowPovertyLevelInThePast12Months"
      unit: "%"
      scaling: 100
      name: "Share of poor in rural areas"
    }
  }
  stat_var_spec {
    key: "illiteracy_rate"
    value {
      stat_var: "Count_Person_Illiterate"
      denom: "Count_Person"
      name: "Illiteracy rate"
      unit: "%"
    }
  }
  stat_var_spec {
    key: "max_temp_diff"
    value {
      stat_var: "DifferenceRelativeToBaseDate2015_Max_Temperature_SSP585"
      unit: "C"
      name: "Max temp relative to 2015, RCP 8.5, SSP 5"
    }
  }
}

categories {
  title: "Education and Poverty"

  blocks {
    title: "Schools per capita"
    columns {
      tiles {
        title: "Schools per capita vs. Poverty rate"
        type: SCATTER
        stat_var_key: "school_pc"
        stat_var_key: "poverty_rate"
      }
    }
    columns {
      tiles {
        title: "Schools per capita vs. Poverty rate"
        type: BIVARIATE
        stat_var_key: "school_pc"
        stat_var_key: "poverty_rate"
      }
    }
  }

  blocks {
    title: "School amenities"
    columns {
      tiles {
        title: "Schools with computers vs. Poverty rate"
        type: SCATTER
        stat_var_key: "school_computer"
        stat_var_key: "poverty_rate"
      }
    }
    columns {
      tiles {
        title: "Schools with computers vs. Poverty rate"
        type: BIVARIATE
        stat_var_key: "school_computer"
        stat_var_key: "poverty_rate"
      }
    }
  }

  blocks {
    columns {
      tiles {
        title: "Schools with toilets vs. Poverty rate"
        type: SCATTER
        stat_var_key: "school_toilet"
        stat_var_key: "poverty_rate"
      }
    }
    columns {
      tiles {
        title: "Schools with toilets vs. Poverty rate"
        type: BIVARIATE
        stat_var_key: "school_toilet"
        stat_var_key: "poverty_rate"
      }
    }
  }

  blocks {
    title: "School dropout rates"
    description: "Percentage of students no longer enrolled at each level of school"
    columns {
      tiles {
        title: "School dropout rates"
        type: BAR
        stat_var_key: "dropout_primary"
        stat_var_key: "dropout_middle"
        stat_var_key: "dropout_secondary"
      }
    }
    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "dropout_primary"
        stat_var_key: "dropout_middle"
        stat_var_key: "dropout_secondary"
      }
    }
  }

  stat_var_spec {
    key: "school_pc"
    value {
      stat_var: "Count_School"
      denom: "Count_Person"
      name: "Schools per capita"
    }
  }
  stat_var_spec {
    key: "poverty_rate"
    value {
      stat_var: "Count_Person_BelowPovertyLevelInThePast12Months_AsFractionOf_Count_Person"
      unit: "%"
      name: "Poverty rate"
    }
  }
  stat_var_spec {
    key: "school_computer"
    value {
      stat_var: "Count_School_HasComputer"
      denom: "Count_School"
      name: "Schools with computers"
      unit: "%"
    }
  }
  stat_var_spec {
    key: "school_toilet"
    value {
      stat_var: "Count_School_HasFunctionalToilet"
      denom: "Count_School"
      name: "Schools with toilets"
      unit: "%"
    }
  }
  stat_var_spec {
    key: "dropout_primary"
    value {
      stat_var: "DropoutRate_Student_PrimarySchool"
      name: "Dropout from primary school"
      unit: "%"
    }
  }
  stat_var_spec {
    key: "dropout_middle"
    value {
      stat_var: "DropoutRate_Student_MiddleSchool"
      name: "Dropout from middle school"
      unit: "%"
    }
  }
  stat_var_spec {
    key: "dropout_secondary"
    value {
      stat_var: "DropoutRate_Student_SecondarySchool"
      name: "Dropout from secondary school"
      unit: "%"
    }
  }
}

categories {
  title: "Health and poverty"

  blocks {
    columns {
      tiles {
        title: "Cumulative COVID-19 cases per capita vs. Poverty rate"
        type: SCATTER
        stat_var_key: "covid_tests_pc"
        stat_var_key: "poverty_rate"
      }
    }
    columns {
      tiles {
        title: "Cumulative COVID-19 deaths per capita vs. Poverty rate"
        type: SCATTER
        stat_var_key: "covid_deaths_pc"
        stat_var_key: "poverty_rate"
      }
    }
  }

  stat_var_spec {
    key: "covid_tests_pc"
    value {
      stat_var: "CumulativeCount_MedicalTest_ConditionCOVID_19_Positive"
      denom: "Count_Person"
      unit: "%"
      scaling: 100
      name: "Cumulative COVID-19 cases per capita"
    }
  }
  stat_var_spec {
    key: "poverty_rate"
    value {
      stat_var: "Count_Person_BelowPovertyLevelInThePast12Months_AsFractionOf_Count_Person"
      unit: "%"
      name: "Poverty rate"
    }
  }
  stat_var_spec {
    key: "covid_deaths_pc"
    value {
      stat_var: "CumulativeCount_MedicalConditionIncident_COVID_19_PatientDeceased"
      denom: "Count_Person"
      unit: "%"
      scaling: 100
      name: "Cumulative COVID-19 deaths per capita"
    }
  }
}

categories {
  title: "Houselessness"

  blocks {
    columns {
      tiles {
        type: HIGHLIGHT
        description: "people in India were houseless (${date})"
        stat_var_key: "houseless_count"
      }
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "houseless_rate"
      }
      tiles {
        title: "Houseless rate vs. Poverty rate"
        type: SCATTER
        stat_var_key: "houseless_rate"
        stat_var_key: "poverty_rate"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "Houseless rate in ${placeName} (${date})"
        stat_var_key: "houseless_rate"
      }
      tiles {
        title: "Houseless rate vs. Poverty rate"
        type: BIVARIATE
        stat_var_key: "houseless_rate"
        stat_var_key: "poverty_rate"
      }
    }
  }

  blocks {
    title: "Houseless by sex"
    description: "Percentage of the houseless population by sex"
    columns {
      tiles {
        type: MAP
        title: "Percentage of the houseless population who are male (${date})"
        stat_var_key: "houseless_rate_male"
      }
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "houseless_rate_male"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "Percentage of the houseless population who are female (${date})"
        stat_var_key: "houseless_rate_female"
      }
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "houseless_rate_female"
      }
    }
    # TODO: Rank by Count_Person_Houseless
    # tiles {
    #   type: BAR
    # }
  }

  blocks {
    title: "Houseless by literacy"
    description: "Percentage of the houseless population by literacy"
    columns {
      tiles {
        type: MAP
        title: "Percentage of the houseless population who are literate (${date})"
        stat_var_key: "houseless_literacy_rate"
      }
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
        }
        stat_var_key: "houseless_literacy_rate"
        stat_var_key: "houseless_illiteracy_rate"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "Percentage of the houseless population who are illiterate (${date})"
        stat_var_key: "houseless_illiteracy_rate"
      }
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
        }
        stat_var_key: "houseless_illiteracy_rate_male"
        stat_var_key: "houseless_illiteracy_rate_female"
      }
    }
  }

  stat_var_spec {
    key: "houseless_rate"
    value {
      stat_var: "Count_Person_Houseless"
      denom: "Count_Person"
      name: "Houseless"
      unit: "%"
      scaling: 100
    }
  }
  stat_var_spec {
    key: "poverty_rate"
    value {
      stat_var: "Count_Person_BelowPovertyLevelInThePast12Months_AsFractionOf_Count_Person"
      unit: "%"
      name: "Poverty rate"
    }
  }
  stat_var_spec {
    key: "houseless_count"
    value {
      stat_var: "Count_Person_Houseless"
      name: "Houseless"
    }
  }
  stat_var_spec {
    key: "houseless_rate_male"
    value {
      stat_var: "Count_Person_Houseless_Male"
      denom: "Count_Person_Houseless"
      unit: "%"
      scaling: 100
      name: "Male"
    }
  }
  stat_var_spec {
    key: "houseless_rate_female"
    value {
      stat_var: "Count_Person_Houseless_Female"
      denom: "Count_Person_Houseless"
      unit: "%"
      scaling: 100
      name: "Female"
    }
  }
  stat_var_spec {
    key: "houseless_literacy_rate"
    value {
      stat_var: "Count_Person_Houseless_Literate"
      denom: "Count_Person_Houseless"
      unit: "%"
      scaling: 100
      name: "Literate"
    }
  }
  stat_var_spec {
    key: "houseless_illiteracy_rate"
    value {
      stat_var: "Count_Person_Houseless_Illiterate"
      denom: "Count_Person_Houseless"
      unit: "%"
      scaling: 100
      name: "Illiterate"
    }
  }
  stat_var_spec {
    key: "houseless_illiteracy_rate_male"
    value {
      stat_var: "Count_Person_Houseless_Illiterate_Male"
      denom: "Count_Person_Houseless_Illiterate"
      unit: "%"
      scaling: 100
      name: "Male, Illiterate"
    }
  }
  stat_var_spec {
    key: "houseless_illiteracy_rate_female"
    value {
      stat_var: "Count_Person_Houseless_Illiterate_Female"
      denom: "Count_Person_Houseless_Illiterate"
      unit: "%"
      scaling: 100
      name: "Female, Illiterate"
    }
  }
}
