# Copyright 2023 TechSoup Global
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## This file specifies the topic page config for poverty in USA


metadata {
  topic_id: "climate"
  topic_name: "Climate Change"

  place_dcid: "country/USA"
  place_group {
    parent_place: "country/USA"
    place_type: "State"
  }
  place_group {
    parent_place: "country/USA"
    place_type: "County"
  }
  contained_place_types {
    key: "Country"
    value: "State"
  }
  contained_place_types {
    key: "State"
    value: "County"
  }
  contained_place_types {
    key: "County"
    value: "CensusTract"
  }
}


############ CATEGORY: Land and Water Use ############

categories {
  title: "Land and Water Use"

  #---------- Land Use ----------# 
  blocks {
    title: "Land Use"
    description: "Over the course of human history, we have altered our local environments to suit our needs. The proportion of forests, bodies of water, protected lands, agricultural fields, are all examples of spaces that are constantly changing, some more than others. Tracking changes in land can be highly valuable when considering the great variety of climate change symptoms we face. The creation of land policy and management strategies to conserve and protect natural landscapes begin with considering data found in the following visualizations."
    columns {tiles {type: MAP title: "Percent of Forest Covered Area (${date})" stat_var_key: "LandCoverFraction_Forest"}}
    columns {tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "LandCoverFraction_Forest"}}
  }
  stat_var_spec {key: "LandCoverFraction_Forest" value {stat_var: "LandCoverFraction_Forest" name: "Percent of Forest Covered Area"}}

  blocks {
    columns {tiles {type: MAP title: "Percent of Permanent Water Covered Area (${date})" stat_var_key: "LandCoverFraction_PermanentWater"}}
    columns {tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "LandCoverFraction_PermanentWater"}}
  }
  stat_var_spec {key: "LandCoverFraction_PermanentWater" value {stat_var: "LandCoverFraction_PermanentWater" name: "Percent of Permanent Water Covered Area"}}
  
  blocks {
    columns {tiles {type: MAP title: "Percent of Seasonal Water Covered Area (${date})" stat_var_key: "LandCoverFraction_SeasonalWater"}}
    columns {tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "LandCoverFraction_SeasonalWater"}}
  }
  stat_var_spec {key: "LandCoverFraction_SeasonalWater" value {stat_var: "LandCoverFraction_SeasonalWater" name: "Percent of Seasonal Water Covered Area" }}

  #---------- Water Use ----------# 
  blocks {
    title: "Water Use"
    description: "Climate change is increasing the stressors on several of earth's water systems. Ground water and reservoirs are driven to depletion through increased demand from a range of extractive processes including domestic and industry usage, and agricultural production. Several lakes in the United States are experiencing lower levels of water, intermittent dry events, and saltwater intrusion. Managing water withdrawal is an important effort to combat water scarcity in the face of accelerating climate change."
    columns {tiles {type: MAP title: "Rate of Water Withdrawal (${date})" stat_var_key: "WithdrawalRate_Water"}}
    columns {tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "WithdrawalRate_Water"}}
  }
  stat_var_spec {key: "WithdrawalRate_Water" value {stat_var: "WithdrawalRate_Water" name: "Rate of Water Withdrawal"}}

}

############ CATEGORY: Observed Temperatures ############

categories {
  title: "Observed Temperatures"


  #---------- Observed Temperatures ----------# 
  blocks {
    description: "According to the National Oceanic and Atmospheric Administration, Earth's temperature has risen at an average of 0.14 degrees Fahrenheit per decade since 1880. Having an authoritative, verifiable baseline for temperatures allows us to look at how temperature has changed so far, and use that information to create helpful climate models that project what temperatures could look like in the future."
    columns {tiles {type: MAP title: "Mean Temperature (${date})" stat_var_key: "Mean_Temperature"}}
    columns {tiles {type: LINE stat_var_key: "Mean_Temperature"}}
  }
  stat_var_spec {key: "Mean_Temperature" value {stat_var: "Mean_Temperature" name: "Mean Temperature"}}
  
  blocks {
    columns {tiles {type: LINE stat_var_key: "Mean_MaxTemperature"}}
    columns {
      tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "Mean_MaxTemperature"}
      tiles {type: MAP title: "Mean maximum temperature Celsius (${date})" stat_var_key: "Mean_MaxTemperature"}
    }
  }
  stat_var_spec {key: "Mean_MaxTemperature" value {stat_var: "Mean_MaxTemperature" name: "Mean maximum temperature (Celsius)"}}

  blocks {
    columns {tiles {type: MAP title: "Mean maximum temperature in forested areas (${date})" stat_var_key: "Mean_MaxTemperature_Forest"}}
    columns {tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "Mean_MaxTemperature_Forest"}}
  }
  stat_var_spec {key: "Mean_MaxTemperature_Forest" value {stat_var: "Mean_MaxTemperature_Forest" name: "Mean maximum temperature in forested areas"}}

}

############ CATEGORY: Observed Emissions ############

categories {
  title: "Observed Emissions"
  description: "As more greenhouse gasses (GHGs) occupy our atmosphere, the more our atmosphere will trap energy from the sun, increasing temperatures globally. Tracking emissions and their source is an integral part to managing our environmental footprint. The phrase \"non biogenic emissions\" refers to any emissions that do not come from a natural source. There are several natural sources of Carbon Dioxide, methane, and other greenhouse gasses. However, human activities contribute a significantly larger amount of GHG emissions to our atmosphere, and are highlighted in the following visualizations."

  blocks {
    columns {tiles {type: MAP title: "Annual Emissions of Non Biogenic Greenhouse Gases (${date})" stat_var_key: "Annual_Emissions_GreenhouseGas_NonBiogenic"}}
    columns {tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "Annual_Emissions_GreenhouseGas_NonBiogenic"}}
  }
  stat_var_spec {key: "Annual_Emissions_GreenhouseGas_NonBiogenic" value {stat_var: "Annual_Emissions_GreenhouseGas_NonBiogenic" name: "Annual Emissions of Non Biogenic Greenhouse Gases"}}

  blocks {
    columns {tiles {type: MAP title: "Annual Emissions of Non Biogenic Carbon Dioxide (${date})" stat_var_key: "Annual_Emissions_CarbonDioxide_NonBiogenic"}}
    columns {tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "Annual_Emissions_CarbonDioxide_NonBiogenic"}}
  }
  stat_var_spec {key: "Annual_Emissions_CarbonDioxide_NonBiogenic" value {stat_var: "Annual_Emissions_CarbonDioxide_NonBiogenic" name: "Annual Emissions of Non Biogenic Carbon Dioxide"}}

  blocks {
    columns {tiles {type: MAP title: "Annual Emissions of Non Biogenic Methane (${date})" stat_var_key: "Annual_Emissions_Methane_NonBiogenic"}}
    columns {tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "Annual_Emissions_Methane_NonBiogenic"}}
  }
  stat_var_spec {key: "Annual_Emissions_Methane_NonBiogenic" value {stat_var: "Annual_Emissions_Methane_NonBiogenic" name: "Annual Emissions of Non Biogenic Methane"}}
}

############ CATEGORY: Climate Hazards ############

categories {
  title: "Climate Hazards"

  #---------- Climate Hazard Damages ----------# 
  blocks {
    title: "Climate Hazard Damages"
    description: "Climate hazards are atmospheric events that cause damage to human settlements or the natural environment. These events include thunderstorms, cyclones, earthquakes, hail, snow, and drought to name a few. In some places of the U.S. there are insurance agencies that are beginning to recognize the costs of climate change and are integrating that into their processes. The following data helps visualize the monetary response to flooding hazards in the United States, sourced through Federal Emergency Management Agency (FEMA)’s National Flood Insurance Program."
    columns {
      tiles {type: LINE title: "Settlement amount of natural hazard insurance for STRUCTURE DAMAGE within the 100 year flood zone (FEMA)" stat_var_key: "SettlementAmount_NaturalHazardInsurance_FEMAHighRiskFloodZone_BuildingStructure_FloodEvent"}
      #tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: false} stat_var_key: "SettlementAmount_NaturalHazardInsurance_FEMAHighRiskFloodZone_BuildingStructure_FloodEvent"}
    }
    #columns {tiles {type: MAP title: "Settlement amount of natural hazard insurance for STRUCTURE DAMAGE within the 100 year flood zone (FEMA) (${date})" stat_var_key: "SettlementAmount_NaturalHazardInsurance_FEMAHighRiskFloodZone_BuildingStructure_FloodEvent"}}
  }
  stat_var_spec {key: "SettlementAmount_NaturalHazardInsurance_FEMAHighRiskFloodZone_BuildingStructure_FloodEvent" value {stat_var: "SettlementAmount_NaturalHazardInsurance_FEMAHighRiskFloodZone_BuildingStructure_FloodEvent" name: "Settlement Amount (USD)"}}

  blocks {
    columns {tiles {type: LINE title: "Settlement amount of natural hazard insurance for HOUSE CONTENT within the 100 year flood zone (FEMA)" stat_var_key: "SettlementAmount_NaturalHazardInsurance_FEMAHighRiskFloodZone_BuildingContents_FloodEvent"}}
    #columns {tiles {type: MAP title: "Settlement amount of natural hazard insurance for HOUSE CONTENT within the 100 year flood zone(FEMA) (${date})" stat_var_key: "SettlementAmount_NaturalHazardInsurance_FEMAHighRiskFloodZone_BuildingContents_FloodEvent"}}
  }
  stat_var_spec {key: "SettlementAmount_NaturalHazardInsurance_FEMAHighRiskFloodZone_BuildingContents_FloodEvent" value {stat_var: "SettlementAmount_NaturalHazardInsurance_FEMAHighRiskFloodZone_BuildingContents_FloodEvent" name: "Settlement Amount (USD)"}}

  #---------- Wildfires ----------# 
  blocks {
    title: "Wildfires"
    description: "Here we want to highlight what different types of data may be available for a specific climate hazard, the wildfire. Wildfires can cover wide expanses of land relatively quickly based on factors like wind speed and dry forest litter abundance. These events not only impact the immediate area, but can impact human health downwind due to ash/smoke traveling through the air."
    columns {tiles {type: MAP title: "Annual Amount of Emissions: Wildfire, Non Biogenic Emission Source, PM 2.5 (${date})" stat_var_key: "Annual_Amount_Emissions_Wildfire_NonBiogenicEmissionSource_PM2.5"}}
    columns {tiles {type: LINE stat_var_key: "Annual_Amount_Emissions_Wildfire_NonBiogenicEmissionSource_PM2.5"}}
  }
  stat_var_spec {key: "Annual_Amount_Emissions_Wildfire_NonBiogenicEmissionSource_PM2.5" value {stat_var: "Annual_Amount_Emissions_Wildfire_NonBiogenicEmissionSource_PM2.5" name: "Annual Amount of Emissions: Wildfire, Non Biogenic Emission Source, PM 2.5"}}

  blocks {
    columns {tiles {type: LINE title: "Dense Smoke" stat_var_key: "Count_DenseSmokeEvent"}}
  }
  stat_var_spec {key: "Count_DenseSmokeEvent" value {stat_var: "Count_DenseSmokeEvent" name: "Cloud of Dense Smoke Event"}}

  blocks {
    columns {tiles {type: LINE title: "Fire Incident Complex" stat_var_key: "Count_FireIncidentComplex"}}
  }
  stat_var_spec {key: "Count_FireIncidentComplex" value {stat_var: "Count_FireIncidentComplex" name: "Count of Fire Incident Complex Event"}}

  blocks {
    columns {tiles {type: MAP title: "Area of forest that burned (Acres) (${date})" stat_var_key: "BurnedArea_FireEvent_Forest"}}
    columns {
      tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: false} stat_var_key: "BurnedArea_FireEvent_Forest"}
      tiles {type: LINE stat_var_key: "BurnedArea_FireEvent_Forest"}
    }
  }
  stat_var_spec {key: "BurnedArea_FireEvent_Forest" value {stat_var: "BurnedArea_FireEvent_Forest" name: "Area of forest that burned (Acres)"}}

  blocks {
    columns {tiles {type: MAP title: "Percent of forest area that experienced high-severity fire (${date})" stat_var_key: "Percent_BurnedArea_FireEvent_Forest_HighSeverity"}}
    columns {
      tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: false} stat_var_key: "Percent_BurnedArea_FireEvent_Forest_HighSeverity"}
      tiles {type: LINE stat_var_key: "Percent_BurnedArea_FireEvent_Forest_HighSeverity"}
    }
  }
  stat_var_spec {key: "Percent_BurnedArea_FireEvent_Forest_HighSeverity" value {stat_var: "Percent_BurnedArea_FireEvent_Forest_HighSeverity" name: "Percent of forest area that experienced high-severity fire"}}

  #---------- Marine and Water Hazards ----------# 
  blocks {
    title: "Marine and Water Hazards"
    description: "Hurricanes and coastal flooding are destructive, and sometimes life threatening events that our coastal communities face. As storms become more intense due to abundant energy in our atmosphere, coastal populations face the decision whether to retreat or to armor their coastline. Datasets like the following track these water hazards to enable us to make better decisions on how to address incoming storms."
    columns {tiles {type: LINE title: "Hurricanes" stat_var_key: "Count_HurricaneEvent"}}
  }
  stat_var_spec {key: "Count_HurricaneEvent" value {stat_var: "Count_HurricaneEvent" name: "Count of Hurricane Event"}}

#  blocks {
#    columns {tiles {type: MAP title: "Count of Flash Flood Event (${date})" stat_var_key: "Count_FlashFloodEvent"}}
#    columns {tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "Count_FlashFloodEvent"}}
#  }
#  stat_var_spec {key: "Count_FlashFloodEvent" value {stat_var: "Count_FlashFloodEvent" name: "Count of Flash Flood Event"}}

  blocks {
    columns {tiles {type: MAP title: "Area of Flood Event (${date})" stat_var_key: "Area_FloodEvent"}}
    columns {tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "Area_FloodEvent"}}
  }
  stat_var_spec {key: "Area_FloodEvent" value {stat_var: "Area_FloodEvent" name: "Area of Flood Event"}}

#  blocks {
#    columns {tiles {type: LINE stat_var_key: "Count_HurricaneTyphoonEvent"}}
#  }
#  stat_var_spec {key: "Count_HurricaneTyphoonEvent" value {stat_var: "Count_HurricaneTyphoonEvent" name: "Count of Hurricane Typhoon Event"}}

#  blocks {
#    columns {tiles {type: LINE stat_var_key: "Count_TropicalDepressionEvent"}}
#  }
#  stat_var_spec {key: "Count_TropicalDepressionEvent" value {stat_var: "Count_TropicalDepressionEvent" name: "Count of Tropical Depression Event"}}

  blocks {
    columns {tiles {type: LINE title: "Tropical Storms" stat_var_key: "Count_TropicalStormEvent"}}
  }
  stat_var_spec {key: "Count_TropicalStormEvent" value {stat_var: "Count_TropicalStormEvent" name: "Count of Tropical Storm Event"}}

  blocks {
    columns {tiles {type: LINE title: "Coastal Floods" stat_var_key: "Count_CoastalFloodEvent"}}
  }
  stat_var_spec {key: "Count_CoastalFloodEvent" value {stat_var: "Count_CoastalFloodEvent" name: "Count of Coastal Flood Event"}}

  #---------- Atmospheric Events/Hazards ----------# 
  blocks {
    title: "Atmospheric Events/Hazards"
    description: "Climate change has a key role in impacting severe weather events worldwide. As our atmosphere traps more heat, extreme weather events will become more likely. The American Meteorological Society released their annual report in 2021 highlighting the occurrence of \"compound events\" where two weather events happen simultaneously. An example of this would be severe heat coupled with lack of rainfall. This weather coupling is a recipe for dry forest litter, which can lead to severe forest fires."
    columns {
      tiles {type: LINE title: "Excessive Heat (105° F or greater)" stat_var_key: "Count_ExcessiveHeatEvent"}
    }
    columns {tiles {type: LINE title: "Heat Waves" stat_var_key: "Count_HeatEvent"}}
  }
  stat_var_spec {key: "Count_ExcessiveHeatEvent" value {stat_var: "Count_ExcessiveHeatEvent" name: "Count of Excessive Heat Event"}}
  stat_var_spec {key: "Count_HeatEvent" value {stat_var: "Count_HeatEvent" name: "Heat Waves"}}

  blocks {
    columns {tiles {type: LINE title: "Extreme Cold Wind Chill" stat_var_key: "Count_ExtremeColdWindChillEvent"}}
    columns {tiles {type: LINE title: "Heavy Rains" stat_var_key: "Count_HeavyRainEvent"}}
  }
  stat_var_spec {key: "Count_ExtremeColdWindChillEvent" value {stat_var: "Count_ExtremeColdWindChillEvent" name: "Count of Extreme Cold Wind Chill Event"}}
  stat_var_spec {key: "Count_HeavyRainEvent" value {stat_var: "Count_HeavyRainEvent" name: "Heavy Rains"}}

  blocks {
    #columns {tiles {type: MAP title: "Droughts (${date})" stat_var_key: "Count_DroughtEvent"}}
    columns {
      tiles {type: LINE title: "Droughts" stat_var_key: "Count_DroughtEvent"}
      #tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "Count_DroughtEvent"}
      #tiles {type: BAR stat_var_key: "Count_DroughtEvent"}
    }
  }
  stat_var_spec {key: "Count_DroughtEvent" value {stat_var: "Count_DroughtEvent" name: "Droughts"}}
}


