# Copyright 2023 TechSoup Global
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## This file specifies the topic page config for poverty in USA


metadata {
  topic_id: "climate"
  topic_name: "Climate Change"

  place_dcid: "country/USA"
  place_group {
    parent_place: "country/USA"
    place_type: "State"
  }
  place_group {
    parent_place: "country/USA"
    place_type: "County"
  }
  contained_place_types {
    key: "Country"
    value: "State"
  }
  contained_place_types {
    key: "State"
    value: "County"
  }
  contained_place_types {
    key: "County"
    value: "CensusTract"
  }
}


############ CATEGORY: Landuse/Remote Sensing/Atmospheric ############

categories {
  title: "Land Use / Remote Sensing / Atmospheric"

  #---------- Land Use ----------# 
  blocks {
    title: "Land Use"
    description: "Land plays an important role in several climatic processes. Tracking land use change can be a valuable tool in a climate researchers toolbox."
    columns {tiles {type: MAP title: "Percent of Forest Covered Area (${date})" stat_var_key: "LandCoverFraction_Forest"}}
    columns {tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "LandCoverFraction_Forest"}}
  }
  stat_var_spec {key: "LandCoverFraction_Forest" value {stat_var: "LandCoverFraction_Forest" name: "Percent of Forest Covered Area"}}

  blocks {
    columns {tiles {type: MAP title: "Percent of Permanent Water Covered Area (${date})" stat_var_key: "LandCoverFraction_PermanentWater"}}
    columns {tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "LandCoverFraction_PermanentWater"}}
  }
  stat_var_spec {key: "LandCoverFraction_PermanentWater" value {stat_var: "LandCoverFraction_PermanentWater" name: "Percent of Permanent Water Covered Area"}}
  
  blocks {
    columns {tiles {type: MAP title: "Percent of Seasonal Water Covered Area (${date})" stat_var_key: "LandCoverFraction_SeasonalWater"}}
    columns {tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "LandCoverFraction_SeasonalWater"}}
  }
  stat_var_spec {key: "LandCoverFraction_SeasonalWater" value {stat_var: "LandCoverFraction_SeasonalWater" name: "Percent of Seasonal Water Covered Area" }}

  #---------- Water Use ----------# 
  blocks {
    title: "Water Use"
    description: "Climate change is impacting our relationship with water. Both water scarcity and accessibility are important issues relating to water conservation and usage."
    columns {tiles {type: MAP title: "Rate of Water Withdrawal (${date})" stat_var_key: "WithdrawalRate_Water"}}
    columns {tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "WithdrawalRate_Water"}}
  }
  stat_var_spec {key: "WithdrawalRate_Water" value {stat_var: "WithdrawalRate_Water" name: "Rate of Water Withdrawal"}}

  #---------- Observed Temperatures ----------# 
  blocks {
    title: "Observed Temperatures"
    description: "Observed temperature datasets can support a great variety of climate change analysis. Tied with its relationship to the changes in our atmosphere, temperature change directly impacts human health."
    columns {tiles {type: MAP title: "Mean Temperature (${date})" stat_var_key: "Mean_Temperature"}}
    columns {tiles {type: LINE stat_var_key: "Mean_Temperature"}}
  }
  stat_var_spec {key: "Mean_Temperature" value {stat_var: "Mean_Temperature" name: "Mean Temperature"}}
  
  blocks {
    columns {tiles {type: LINE stat_var_key: "Mean_MaxTemperature"}}
    columns {
      tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "Mean_MaxTemperature"}
      tiles {type: MAP title: "Mean maximum temperature (${date})" stat_var_key: "Mean_MaxTemperature"}
    }
  }
  stat_var_spec {key: "Mean_MaxTemperature" value {stat_var: "Mean_MaxTemperature" name: "Mean maximum temperature"}}

  blocks {
    columns {tiles {type: MAP title: "Mean maximum temperature in forested areas (${date})" stat_var_key: "Mean_MaxTemperature_Forest"}}
    columns {tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "Mean_MaxTemperature_Forest"}}
  }
  stat_var_spec {key: "Mean_MaxTemperature_Forest" value {stat_var: "Mean_MaxTemperature_Forest" name: "Mean maximum temperature in forested areas"}}

}

############ CATEGORY: Observed Emissions ############

categories {
  title: "Observed Emissions"
  description: "Non biogenic emissions are any emissions that do not come from a natural source. There are several natural sources of Carbon dioxide, methane, and other commonly emitted greenhouse gasses (GHG’s). However, human activities contribute a significantly larger amount of GHG emissions to our atmosphere, and are highlighted in the following visualizations."

  blocks {
    columns {tiles {type: MAP title: "Annual Emissions of Non Biogenic Greenhouse Gases (${date})" stat_var_key: "Annual_Emissions_GreenhouseGas_NonBiogenic"}}
    columns {tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "Annual_Emissions_GreenhouseGas_NonBiogenic"}}
  }
  stat_var_spec {key: "Annual_Emissions_GreenhouseGas_NonBiogenic" value {stat_var: "Annual_Emissions_GreenhouseGas_NonBiogenic" name: "Annual Emissions of Non Biogenic Greenhouse Gases"}}

  blocks {
    columns {tiles {type: MAP title: "Annual Emissions of Non Biogenic Carbon Dioxide (${date})" stat_var_key: "Annual_Emissions_CarbonDioxide_NonBiogenic"}}
    columns {tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "Annual_Emissions_CarbonDioxide_NonBiogenic"}}
  }
  stat_var_spec {key: "Annual_Emissions_CarbonDioxide_NonBiogenic" value {stat_var: "Annual_Emissions_CarbonDioxide_NonBiogenic" name: "Annual Emissions of Non Biogenic Carbon Dioxide"}}

  blocks {
    columns {tiles {type: MAP title: "Annual Emissions of Non Biogenic Methane (${date})" stat_var_key: "Annual_Emissions_Methane_NonBiogenic"}}
    columns {tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "Annual_Emissions_Methane_NonBiogenic"}}
  }
  stat_var_spec {key: "Annual_Emissions_Methane_NonBiogenic" value {stat_var: "Annual_Emissions_Methane_NonBiogenic" name: "Annual Emissions of Non Biogenic Methane"}}
}

############ CATEGORY: Climate Hazards ############

categories {
  title: "Climate Hazards"

  #---------- Climate Hazard Damages ----------# 
  blocks {
    title: "Climate Hazard Damages"
    description: "The Federal Emergency Management Agency (FEMA) manages the National Flood Insurance Program (NFIP) to support communities recovering from flood damages. Programs like this are vital to communities facing climate hazards and the recovery process."
    columns {
      tiles {type: LINE stat_var_key: "SettlementAmount_NaturalHazardInsurance_FEMAHighRiskFloodZone_BuildingStructure_FloodEvent"}
      tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: false} stat_var_key: "SettlementAmount_NaturalHazardInsurance_FEMAHighRiskFloodZone_BuildingStructure_FloodEvent"}
    }
    columns {tiles {type: MAP title: "Settlement amount of natural hazard insurance for STRUCTURE DAMAGE within the 100 year flood zone(FEMA) (${date})" stat_var_key: "SettlementAmount_NaturalHazardInsurance_FEMAHighRiskFloodZone_BuildingStructure_FloodEvent"}}
  }
  stat_var_spec {key: "SettlementAmount_NaturalHazardInsurance_FEMAHighRiskFloodZone_BuildingStructure_FloodEvent" value {stat_var: "SettlementAmount_NaturalHazardInsurance_FEMAHighRiskFloodZone_BuildingStructure_FloodEvent" name: "Settlement amount of natural hazard insurance for STRUCTURE DAMAGE within the 100 year flood zone(FEMA)"}}

  blocks {
    columns {tiles {type: LINE stat_var_key: "SettlementAmount_NaturalHazardInsurance_FEMAHighRiskFloodZone_BuildingContents_FloodEvent"}}
    columns {tiles {type: MAP title: "Settlement amount of natural hazard insurance for HOUSE CONTENT within the 100 year flood zone(FEMA) (${date})" stat_var_key: "SettlementAmount_NaturalHazardInsurance_FEMAHighRiskFloodZone_BuildingContents_FloodEvent"}}
  }
  stat_var_spec {key: "SettlementAmount_NaturalHazardInsurance_FEMAHighRiskFloodZone_BuildingContents_FloodEvent" value {stat_var: "SettlementAmount_NaturalHazardInsurance_FEMAHighRiskFloodZone_BuildingContents_FloodEvent" name: "Settlement amount of natural hazard insurance for HOUSE CONTENT within the 100 year flood zone(FEMA)"}}

  #---------- Wildfires ----------# 
  blocks {
    title: "Wildfires"
    description: "The increase in dry leaf litter and water scarcity has significant implications for the future of wildfires in the United States. Forestry managers highly value the tracking of wildfires to prevent and protect."
    columns {tiles {type: MAP title: "Wildfires (${date})" stat_var_key: "Count_WildfireEvent"}}
    columns {tiles {type: LINE stat_var_key: "Count_WildfireEvent"}}
  }
  stat_var_spec {key: "Count_WildfireEvent" value {stat_var: "Count_WildfireEvent" name: "Wildfires"}}

  blocks {
    columns {tiles {type: LINE stat_var_key: "Count_DenseSmokeEvent"}}
  }
  stat_var_spec {key: "Count_DenseSmokeEvent" value {stat_var: "Count_DenseSmokeEvent" name: "Cloud of Dense Smoke Event"}}

  blocks {
    columns {tiles {type: LINE stat_var_key: "Count_FireIncidentComplex"}}
  }
  stat_var_spec {key: "Count_FireIncidentComplex" value {stat_var: "Count_FireIncidentComplex" name: "Count of Fire Incident Complex Event"}}

  blocks {
    columns {tiles {type: MAP title: "Area of forest that burned (Acres) (${date})" stat_var_key: "BurnedArea_FireEvent_Forest"}}
    columns {
      tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: false} stat_var_key: "BurnedArea_FireEvent_Forest"}
      tiles {type: LINE stat_var_key: "BurnedArea_FireEvent_Forest"}
    }
  }
  stat_var_spec {key: "BurnedArea_FireEvent_Forest" value {stat_var: "BurnedArea_FireEvent_Forest" name: "Area of forest that burned (Acres)"}}

  blocks {
    columns {tiles {type: MAP title: "Percent of forest area that experienced high-severity fire (${date})" stat_var_key: "Percent_BurnedArea_FireEvent_Forest_HighSeverity"}}
    columns {
      tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: false} stat_var_key: "Percent_BurnedArea_FireEvent_Forest_HighSeverity"}
      tiles {type: LINE stat_var_key: "Percent_BurnedArea_FireEvent_Forest_HighSeverity"}
    }
  }
  stat_var_spec {key: "Percent_BurnedArea_FireEvent_Forest_HighSeverity" value {stat_var: "Percent_BurnedArea_FireEvent_Forest_HighSeverity" name: "Percent of forest area that experienced high-severity fire"}}

  #---------- Marine and Water Hazards ----------# 
  blocks {
    title: "Marine and Water Hazards"
    description: "Coastal and water hazards introduce a myriad of challenges for a community. These hazards can be some of the most damaging to property and human health."
    columns {tiles {type: LINE stat_var_key: "Count_HurricaneEvent"}}
  }
  stat_var_spec {key: "Count_HurricaneEvent" value {stat_var: "Count_HurricaneEvent" name: "Count of Hurricane Event"}}

  blocks {
    columns {tiles {type: MAP title: "Count of Flash Flood Event (${date})" stat_var_key: "Count_FlashFloodEvent"}}
    columns {tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "Count_FlashFloodEvent"}}
  }
  stat_var_spec {key: "Count_FlashFloodEvent" value {stat_var: "Count_FlashFloodEvent" name: "Count of Flash Flood Event"}}

  blocks {
    columns {tiles {type: MAP title: "Count of Flood Event (${date})" stat_var_key: "Count_FloodEvent"}}
    columns {tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "Count_FloodEvent"}}
  }
  stat_var_spec {key: "Count_FloodEvent" value {stat_var: "Count_FloodEvent" name: "Count of Flood Event"}}

  blocks {
    columns {tiles {type: LINE stat_var_key: "Count_HurricaneTyphoonEvent"}}
  }
  stat_var_spec {key: "Count_HurricaneTyphoonEvent" value {stat_var: "Count_HurricaneTyphoonEvent" name: "Count of Hurricane Typhoon Event"}}

  blocks {
    columns {tiles {type: LINE stat_var_key: "Count_TropicalDepressionEvent"}}
  }
  stat_var_spec {key: "Count_TropicalDepressionEvent" value {stat_var: "Count_TropicalDepressionEvent" name: "Count of Tropical Depression Event"}}

  blocks {
    columns {tiles {type: LINE stat_var_key: "Count_TropicalStormEvent"}}
  }
  stat_var_spec {key: "Count_TropicalStormEvent" value {stat_var: "Count_TropicalStormEvent" name: "Count of Tropical Storm Event"}}

  blocks {
    columns {tiles {type: LINE stat_var_key: "Count_CoastalFloodEvent"}}
  }
  stat_var_spec {key: "Count_CoastalFloodEvent" value {stat_var: "Count_CoastalFloodEvent" name: "Count of Coastal Flood Event"}}

  #---------- Atmospheric Events/Hazards ----------# 
  blocks {
    title: "Atmospheric Events/Hazards"
    description: "As our atmosphere traps more energy from the sun due to an increase in GHG’s, we face a range of symptoms including increased temperature, intense storms, and excessive rain events."
    columns {
      tiles {type: LINE stat_var_key: "Count_ExcessiveHeatEvent"}
      tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "Count_ExcessiveHeatEvent"}
    }
    columns {tiles {type: MAP title: "Count of Excessive Heat Event (${date})" stat_var_key: "Count_ExcessiveHeatEvent"}}
  }
  stat_var_spec {key: "Count_ExcessiveHeatEvent" value {stat_var: "Count_ExcessiveHeatEvent" name: "Count of Excessive Heat Event"}}

  blocks {
    columns {tiles {type: MAP title: "Count of Extreme Cold Wind Chill Event (${date})" stat_var_key: "Count_ExtremeColdWindChillEvent"}}
    columns {tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "Count_ExtremeColdWindChillEvent"}}
  }
  stat_var_spec {key: "Count_ExtremeColdWindChillEvent" value {stat_var: "Count_ExtremeColdWindChillEvent" name: "Count of Extreme Cold Wind Chill Event"}}
  
  blocks {
    columns {tiles {type: MAP title: "Heat Waves (${date})" stat_var_key: "Count_HeatEvent"}}
    columns {tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "Count_HeatEvent"}}
  }
  stat_var_spec {key: "Count_HeatEvent" value {stat_var: "Count_HeatEvent" name: "Heat Waves"}}

  blocks {
    columns {tiles {type: MAP title: "Heavy Rains (${date})" stat_var_key: "Count_HeavyRainEvent"}}
    columns {tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "Count_HeavyRainEvent"}}
  }
  stat_var_spec {key: "Count_HeavyRainEvent" value {stat_var: "Count_HeavyRainEvent" name: "Heavy Rains"}}

  blocks {
    columns {tiles {type: MAP title: "Count of Heat Temperature Event (${date})" stat_var_key: "Count_HeatTemperatureEvent"}}
    columns {tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "Count_HeatTemperatureEvent"}}
  }
  stat_var_spec {key: "Count_HeatTemperatureEvent" value {stat_var: "Count_HeatTemperatureEvent" name: "Count of Heat Temperature Event"}}

  blocks {
    columns {tiles {type: MAP title: "Droughts (${date})" stat_var_key: "Count_DroughtEvent"}}
    columns {
      tiles {type: RANKING ranking_tile_spec {show_highest: true show_lowest: true} stat_var_key: "Count_DroughtEvent"}
      tiles {type: BAR stat_var_key: "Count_DroughtEvent"}
    }
  }
  stat_var_spec {key: "Count_DroughtEvent" value {stat_var: "Count_DroughtEvent" name: "Droughts"}}
}


