# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tool_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftool_info.proto\x12\x0b\x64\x61tacommons\"(\n\x0bInfoExample\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\"\\\n\nInfoBullet\x12\x0e\n\x06header\x18\x01 \x01(\t\x12\x13\n\x0bpreposition\x18\x02 \x01(\t\x12)\n\x07\x65xample\x18\x03 \x03(\x0b\x32\x18.datacommons.InfoExample\"1\n\x08ToolInfo\x12%\n\x04info\x18\x01 \x03(\x0b\x32\x17.datacommons.InfoBulletb\x06proto3')



_INFOEXAMPLE = DESCRIPTOR.message_types_by_name['InfoExample']
_INFOBULLET = DESCRIPTOR.message_types_by_name['InfoBullet']
_TOOLINFO = DESCRIPTOR.message_types_by_name['ToolInfo']
InfoExample = _reflection.GeneratedProtocolMessageType('InfoExample', (_message.Message,), {
  'DESCRIPTOR' : _INFOEXAMPLE,
  '__module__' : 'tool_info_pb2'
  # @@protoc_insertion_point(class_scope:datacommons.InfoExample)
  })
_sym_db.RegisterMessage(InfoExample)

InfoBullet = _reflection.GeneratedProtocolMessageType('InfoBullet', (_message.Message,), {
  'DESCRIPTOR' : _INFOBULLET,
  '__module__' : 'tool_info_pb2'
  # @@protoc_insertion_point(class_scope:datacommons.InfoBullet)
  })
_sym_db.RegisterMessage(InfoBullet)

ToolInfo = _reflection.GeneratedProtocolMessageType('ToolInfo', (_message.Message,), {
  'DESCRIPTOR' : _TOOLINFO,
  '__module__' : 'tool_info_pb2'
  # @@protoc_insertion_point(class_scope:datacommons.ToolInfo)
  })
_sym_db.RegisterMessage(ToolInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INFOEXAMPLE._serialized_start=32
  _INFOEXAMPLE._serialized_end=72
  _INFOBULLET._serialized_start=74
  _INFOBULLET._serialized_end=166
  _TOOLINFO._serialized_start=168
  _TOOLINFO._serialized_end=217
# @@protoc_insertion_point(module_scope)
