steps:
  - name: 'gcr.io/datcom-ci/percy-runner:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd /app
        export PERCY_TOKEN="$percy_token"
        export PERCY_BRANCH="${_ENVIRONMENT}"
        export PERCY_TARGET_BRANCH="production"
        percy exec -- python3 per_environment_percy_snapshots.py --env=${_ENVIRONMENT}
    secretEnv: ['percy_token']

availableSecrets:
  secretManager:
    - versionName: projects/879489846695/secrets/PERCY_TOKEN_RELEASES/versions/latest
      env: 'percy_token'

substitutions:
  _ENVIRONMENT: 'production'

# Add this section to increase machine resources
options:
  machineType: 'E2_HIGHCPU_8'