# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## This file specifies the config for charts on event pages.

metadata {
  topic_id: "event"
  # Contained_place_types set in routes/event.py.
}

categories {
  title: "Other natural disasters in ${placeName}"
  blocks {
    columns {
      tiles {
        type: LINE
        title: "Number of droughts in ${placeName}"
        stat_var_key: "count_drought"
      }
    }
    columns {
      tiles {
        type: LINE
        title: "Number of earthquakes in ${placeName}"
        stat_var_key: "count_earthquake"
      }
    }
    columns {
      tiles {
        type: LINE
        title: "Number of fires in ${placeName}"
        stat_var_key: "count_fire"
      }
    }
    columns {
      tiles {
        type: LINE
        title: "Number of floods in ${placeName}"
        stat_var_key: "count_flood"
      }
    }
    columns {
      tiles {
        type: LINE
        title: "Number of wet bulb temperature events in ${placeName}"
        stat_var_key: "count_wetbulbtemperature"
      }
    }
  }
  stat_var_spec {
    key: "count_drought"
    value {
      stat_var: "Count_DroughtEvent"
      name: "Droughts"
    }
  }
  stat_var_spec {
    key: "count_earthquake"
    value {
      stat_var: "Count_EarthquakeEvent"
      name: "Earthquakes"
    }
  }
  stat_var_spec {
    key: "count_fire"
    value {
      stat_var: "Count_FireEvent"
      name: "Fires"
    }
  }
  stat_var_spec {
    key: "count_flood"
    value {
      stat_var: "Count_FloodEvent"
      name: "Floods"
    }
  }
  stat_var_spec {
    key: "count_wetbulbtemperature"
    value {
      stat_var: "Count_WetBulbTemperatureEvent"
      name: "Wet bulb temperature events"
    }
  }
}

categories {
  title: "More information about ${placeName}"

  blocks {
    columns {
      tiles {
        type: LINE
        title: "Population of ${placeName}"
        stat_var_key: "population"
      }
    }
    columns {
      tiles {
        type: LINE
        title: "Population growth rate in ${placeName}"
        stat_var_key: "pop_growth"
      }
    }
    columns {
      tiles {
        type: LINE
        title: "Population density (people per km²) in ${placeName}"
        stat_var_key: "pop_density"
      }
    }
    columns {
      tiles {
        type: LINE
        title: "Median individual income in ${placeName}"
        stat_var_key: "median_income"
      }
    }
    columns {
      tiles {
        type: LINE
        title: "Gini index in ${placeName}"
        stat_var_key: "gini_index"
      }
    }
    columns {
      tiles {
        type: LINE
        title: "GDP per capita in ${placeName}"
        stat_var_key: "gdp_percapita"
      }
    }
    columns {
      tiles {
        type: LINE
        title: "Poverty rate of ${placeName}"
        stat_var_key: "poverty_rate"
      }
    }
    columns {
      tiles {
        type: LINE
        title: "Life expectancy of ${placeName}"
        stat_var_key: "life_expectancy"
      }
    }
    columns {
      tiles {
        type: LINE
        title: "Children in employment in ${placeName}"
        stat_var_key: "child_employment"
      }
    }
    columns {
      tiles {
        type: LINE
        title: "Infant mortality of ${placeName}"
        stat_var_key: "infant_mortality"
      }
    }
  }

  stat_var_spec {
    key: "population"
    value {
      stat_var: "Count_Person"
      name: "Population"
    }
  }
  stat_var_spec {
    key: "pop_growth"
    value {
      stat_var: "GrowthRate_Count_Person"
      name: "Population Growth Rate"
    }
  }
  stat_var_spec {
    key: "pop_density"
    value {
      stat_var: "Count_Person_PerArea"
      name: "Population Density"
    }
  }
  stat_var_spec {
    key: "median_income"
    value {
      stat_var: "Median_Income_Person"
      name: "Median individual income"
    }
  }
  stat_var_spec {
    key: "poverty_rate"
    value {
      stat_var: "Count_Person_BelowPovertyLevelInThePast12Months"
      denom: "Count_Person"
      name: "Poverty rate"
      unit: "%"
    }
  }
  stat_var_spec {
    key: "life_expectancy"
    value {
      stat_var: "LifeExpectancy_Person"
      name: "Life expectancy"
      unit: "Years"
    }
  }
  stat_var_spec {
    key: "gini_index"
    value {
      stat_var: "GiniIndex_EconomicActivity"
      name: "Gini index"
    }
  }
  stat_var_spec {
    key: "infant_mortality"
    value {
      stat_var: "Count_Death_0Years_AsFractionOf_Count_BirthEvent_LiveBirth"
      name: "Infant mortality"
      unit: "%"
    }
  }
  stat_var_spec {
    key: "gdp_percapita"
    value {
      stat_var: "Amount_EconomicActivity_GrossDomesticProduction_Nominal_PerCapita"
      name: "GDP per capita"
      unit: "USD"
    }
  }
  stat_var_spec {
    key: "child_employment"
    value {
      stat_var: "Count_Person_7To14Years_Employed_AsFractionOf_Count_Person_7To14Years"
      name: "Child employment"
      unit: "%"
    }
  }
}