# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## This file specifies the config for sustainability explorer.

metadata {
  topic_id: "sustainability_explorer"
  # Contained_place_types set in routes/event.py.
}

categories {
  title: "Natural disasters"
  description: "More at [the disaster dashboard](/disasters/${placeDcid})"
  blocks {
    columns {
      tiles {}
    }
  }
}

categories {
  title: "Environment"
  blocks {
    title: "Air quality"
    columns {
      tiles {
        type: LINE
        title: "Air quality index"
        stat_var_key: "aqi"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "Air quality index"
        stat_var_key: "aqi"
      }
    }
  }

  blocks {
    title: "Temperature"
    columns {
      tiles {
        type: LINE
        title: "Projected max temperature change under RCP 2.6 (based on year 2006)"
        stat_var_key: "temp_rcp26"
      }
      tiles {
        type: MAP
        title: "Projected max temperature change under RCP 2.6 (based on year 2006)"
        stat_var_key: "temp_rcp26"
      }
    }
    columns {
      tiles {
        type: LINE
        title: "Projected max temperature change under RCP 4.5 (based on year 2006)"
        stat_var_key: "temp_rcp45"
      }
      tiles {
        type: MAP
        title: "Projected max temperature change under RCP 4.5 (based on year 2006)"
        stat_var_key: "temp_rcp45"
      }
    }
    columns {
      tiles {
        type: LINE
        title: "Projected max temperature change under RCP 4.5, SSP 2 (based on year 2015)"
        stat_var_key: "temp_ssp245"
      }
      tiles {
        type: MAP
        title: "Projected max temperature change under RCP 4.5, SSP 2 (based on year 2015)"
        stat_var_key: "temp_ssp245"
      }
    }
    columns {
      tiles {
        type: LINE
        title: "Projected max temperature change under RCP 8.5, SSP 5 (based on year 2015)"
        stat_var_key: "temp_ssp585"
      }
      tiles {
        type: MAP
        title: "Projected max temperature change under RCP 8.5, SSP 5 (based on year 2015)"
        stat_var_key: "temp_ssp585"
      }
    }
  }

  blocks {
    title: "Energy"
    columns {
      tiles {
        title: "Energy consumption (kg of oil equivalent per capita)"
        type: LINE
        stat_var_key: "energy_consumption_pc"
      }
    }
    columns {
      tiles {
        title: "Electricity consumption per capita",
        type: LINE
        stat_var_key: "energy_consumption"
      }
    }
    columns {
      tiles {
        title: "Electricity generation per capita",
        type: LINE
        stat_var_key: "energy_generation"
      }
    }
    columns {
      tiles {
        title: "Annual average retail price of electricity, all sectors"
        type: LINE
        stat_var_key: "electricity_price"
      }
    }
  }

  stat_var_spec {
    key: "aqi"
    value {
      stat_var: "AirQualityIndex_AirPollutant"
      name: "AQI"
    }
  }
  stat_var_spec {
    key: "temp_rcp26"
    value {
      stat_var: "DifferenceRelativeToBaseDate2006_Max_Temperature_RCP26"
      unit: "°C"
      name: "Projected max temp. change, RCP 2.6 (based on 2006)"
    }
  }
  stat_var_spec {
    key: "temp_rcp45"
    value {
      stat_var: "DifferenceRelativeToBaseDate2006_Max_Temperature_RCP45"
      unit: "°C"
      name: "Projected max temp. change, RCP 4.5 (based on 2006)"
    }
  }
  stat_var_spec {
    key: "temp_ssp245"
    value {
      stat_var: "DifferenceRelativeToBaseDate2015_Max_Temperature_SSP245"
      unit: "°C"
      name: "Projected max temp. change, RCP 4.5, SSP 2 (based on 2015)"
    }
  }
  stat_var_spec {
    key: "temp_ssp585"
    value {
      stat_var: "DifferenceRelativeToBaseDate2015_Max_Temperature_SSP585"
      unit: "°C"
      name: "Projected max temp. change, RCP 8.5, SSP 5 (based on 2015)"
    }
  }
  stat_var_spec {
    key: "energy_consumption_pc"
    value {
      stat_var: "Amount_Consumption_Energy_PerCapita"
      unit: "kgoe"
      name: "Electricity consumption per capita"
    }
  }
  stat_var_spec {
    key: "energy_generation"
    value {
      stat_var: "Annual_Generation_Electricity"
      denom: "Count_Person"
      name: "Electricity generation per capita"
      unit: "kWh"
    }
  }
  stat_var_spec {
    key: "energy_consumption"
    value {
      stat_var: "Amount_Consumption_Electricity_PerCapita"
      name: "Electricity consumption per capita"
      unit: "kWh"
    }
  }
  stat_var_spec {
    key: "electricity_price"
    value {
      stat_var: "Annual_Average_RetailPrice_Electricity"
      unit: "¢/kWh"
      name: "Annual average retail price of electricity, all sectors"
    }
  }
}

categories {
  title: "Health"
  blocks {
    columns {
      tiles {
        type: LINE
        title: "Life expectancy (years)"
        stat_var_key: "life_expectancy"
      }
    }
    columns {
      tiles {
        type: LINE
        title: "Infant mortality rate"
        stat_var_key: "infant_mortality"
      }
    }
    columns {
      tiles {
        type: LINE
        title: "Infant mortality rate, by gender"
        stat_var_key: "infant_mortality_male"
        stat_var_key: "infant_mortality_female"
      }
    }
    columns {
      tiles {
        type: LINE
        title: "Wasting among children under 5"
        stat_var_key: "wasting"
      }
    }
    columns {
      tiles {
        type: LINE
        title: "Wasting among children under 5, by gender"
        stat_var_key: "wasting_male"
        stat_var_key: "wasting_female"
      }
    }
    columns {
      tiles {
        type: LINE
        title: "Alcohol consumption per capita (annual)"
        stat_var_key: "alcohol"
      }
    }
    columns {
      tiles {
        type: BAR
        title: "Mortality events"
        stat_var_key: "death_circulatory"
        stat_var_key: "death_neoplasms"
        stat_var_key: "death_respiratory"
        stat_var_key: "death_external"
        stat_var_key: "death_nervous"
        comparison_places: "self"
      }
    }
    columns {
      tiles {
        type: BAR
        title: "Health outcomes"
        stat_var_key: "high_cholesterol"
        stat_var_key: "high_blood_pressure"
        stat_var_key: "arthritis"
        stat_var_key: "mental_health"
        stat_var_key: "physical_health"
        comparison_places: "self"
      }
    }
  }

  stat_var_spec {
    key: "life_expectancy"
    value {
      stat_var: "LifeExpectancy_Person"
      name: "Life expectancy"
      unit: "Years"
    }
  }
  stat_var_spec {
    key: "death_circulatory"
    value {
      stat_var: "Count_Death_DiseasesOfTheCirculatorySystem"
      name: "Circulatory system"
    }
  }
  stat_var_spec {
    key: "death_neoplasms"
    value {
      stat_var: "Count_Death_Neoplasms"
      name: "Neoplasms"
    }
  }
  stat_var_spec {
    key: "death_respiratory"
    value {
      stat_var: "Count_Death_DiseasesOfTheRespiratorySystem"
      name: "Respiratory system"
    }
  }
  stat_var_spec {
    key: "death_external"
    value {
      stat_var: "Count_Death_ExternalCauses"
      name: "External causes"
    }
  }
  stat_var_spec {
    key: "death_nervous"
    value {
      stat_var: "Count_Death_DiseasesOfTheNervousSystem"
      name: "Nervous system"
    }
  }
  stat_var_spec {
    key: "infant_mortality_male"
    value {
      stat_var: "Count_Death_0Years_Male_AsFractionOf_Count_BirthEvent_LiveBirth_Male"
      name: "Male"
      scaling: 0.1
      unit: "%"
    }
  }
  stat_var_spec {
    key: "infant_mortality_female"
    value {
      stat_var: "Count_Death_0Years_Female_AsFractionOf_Count_BirthEvent_LiveBirth_Female"
      name: "Female"
      scaling: 0.1
      unit: "%"
    }
  }
  stat_var_spec {
    key: "infant_mortality"
    value {
      stat_var: "Count_Death_0Years_AsFractionOf_Count_BirthEvent_LiveBirth"
      name: "Infant mortality rate"
      scaling: 0.1
      unit: "%"
    }
  }
  stat_var_spec {
    key: "wasting"
    value {
      stat_var: "Count_Person_Upto4Years_Wasting_AsFractionOf_Count_Person_Upto4Years"
      name: "Wasting under 5 years old"
      unit: "%"
    }
  }
  stat_var_spec {
    key: "wasting_male"
    value {
      stat_var: "Count_Person_Upto4Years_Male_Wasting_AsFractionOf_Count_Person_Upto4Years_Male"
      name: "Male"
      unit: "%"
    }
  }
  stat_var_spec {
    key: "wasting_female"
    value {
      stat_var: "Count_Person_Upto4Years_Female_Wasting_AsFractionOf_Count_Person_Upto4Years_Female"
      name: "Female"
      unit: "%"
    }
  }
  stat_var_spec {
    key: "alcohol"
    value {
      stat_var: "Amount_Consumption_Alcohol_15OrMoreYears_AsFractionOf_Count_Person_15OrMoreYears"
      name: "Annual alcohol consumption per person"
      unit: "L"
    }
  }
  stat_var_spec {
    key: "high_cholesterol"
    value {
      stat_var: "Percent_Person_WithHighCholesterol"
      name: "High cholesterol"
      unit: "%"
    }
  }
  stat_var_spec {
    key: "high_blood_pressure"
    value {
      stat_var: "Percent_Person_WithHighBloodPressure"
      name: "High blood pressure"
      unit: "%"
    }
  }
  stat_var_spec {
    key: "arthritis"
    value {
      stat_var: "Percent_Person_WithArthritis"
      name: "Arthritis"
      unit: "%"
    }
  }
  stat_var_spec {
    key: "mental_health"
    value {
      stat_var: "Percent_Person_WithMentalHealthNotGood"
      name: "Poor mental health"
      unit: "%"
    }
  }
  stat_var_spec {
    key: "physical_health"
    value {
      stat_var: "Percent_Person_WithPhysicalHealthNotGood"
      name: "Poor physical health"
      unit: "%"
    }
  }
  # stat_var_spec {
  #   key:
  #   value {
  #     stat_var:
  #   }
  # }
}

categories {
  title: "Shelter"
  blocks {
    columns {
      tiles {}
    }
  }
}

categories {
  title: "Economics"
  blocks {
    columns {
      tiles {}
    }
  }
}