# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## This file specifies the config for sustainability explorer.

metadata {
  topic_id: "sustainability_explorer"
  contained_place_types {
    key: "Planet"
    value: "Country"
  }
  contained_place_types {
    key: "Continent"
    value: "Country"
  }
  contained_place_types {
    key: "Country"
    value: "AdministrativeArea1"
  }
  contained_place_types {
    key: "AdministrativeArea1"
    value: "AdministrativeArea2"
  }
}

categories {
  title: "Natural disasters"
  description: "More at [the disaster dashboard](/disasters/${placeDcid})"
  blocks {
    columns {
      tiles {}
    }
  }
}

categories {
  title: "Environment"
  blocks {
    title: "Air quality"
    columns {
      tiles {
        type: LINE
        title: "Air quality index"
        stat_var_key: "aqi"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "Air quality index"
        stat_var_key: "aqi"
      }
    }
  }
  blocks {
    title: "Temperature"
    columns {
      tiles {
        type: LINE
        title: "Projected max temperature change under RCP 2.6 (based on year 2006)"
        stat_var_key: "temp_rcp26"
      }
    }
    columns {
      tiles {
        type: LINE
        title: "Projected max temperature change under RCP 4.5 (based on year 2006)"
        stat_var_key: "temp_rcp45"
      }
    }
    columns {
      tiles {
        type: LINE
        title: "Projected max temperature change under RCP 4.5, SSP 2 (based on year 2015)"
        stat_var_key: "temp_ssp245"
      }
    }
    columns {
      tiles {
        type: LINE
        title: "Projected max temperature change under RCP 8.5, SSP 5 (based on year 2015)"
        stat_var_key: "temp_ssp585"
      }
    }
  }
  blocks {
    title: "Energy"
    columns {
      tiles {
        title: "Energy use (kg of oil equivalent per capita)"
        type: LINE
        stat_var_key: "energy_consumption_pc"
      }
    }
    columns {
      tiles {
        title: "Electricity generation per capita",
        type: LINE
        stat_var_key: "energy_generation"
      }
    }
  }
  stat_var_spec {
    key: "aqi"
    value {
      stat_var: "AirQualityIndex_AirPollutant"
      name: "AQI"
    }
  }
  stat_var_spec {
    key: "temp_rcp26"
    value {
      stat_var: "DifferenceRelativeToBaseDate2006_Max_Temperature_RCP26"
      unit: "°C"
      name: "Projected max temp. change, RCP 2.6 (based on 2006)"
    }
  }
  stat_var_spec {
    key: "temp_rcp45"
    value {
      stat_var: "DifferenceRelativeToBaseDate2006_Max_Temperature_RCP45"
      unit: "°C"
      name: "Projected max temp. change, RCP 4.5 (based on 2006)"
    }
  }
  stat_var_spec {
    key: "temp_ssp245"
    value {
      stat_var: "DifferenceRelativeToBaseDate2015_Temperature_SSP245"
      unit: "°C"
      name: "Projected max temp. change, RCP 4.5, SSP 2 (based on 2015)"
    }
  }
  stat_var_spec {
    key: "temp_ssp585"
    value {
      stat_var: "DifferenceRelativeToBaseDate2015_Temperature_SSP585"
      unit: "°C"
      name: "Projected max temp. change, RCP 8.5, SSP 5 (based on 2015)"
    }
  }
  stat_var_spec {
    key: "energy_consumption_pc"
    value {
      stat_var: "Amount_Consumption_Energy_PerCapita"
      unit: "kgoe"
    }
  }
  stat_var_spec {
    key: "energy_generation"
    value {
      stat_var: "Annual_Generation_Electricity"
      denom: "Count_Person"
      unit: "kWh / person"
    }
  }
  # stat_var_spec {
  #   key:
  #   value {
  #     stat_var:
  #   }
  # }
  # stat_var_spec {
  #   key:
  #   value {
  #     stat_var:
  #   }
  # }
  # stat_var_spec {
  #   key:
  #   value {
  #     stat_var:
  #   }
  # }
  # stat_var_spec {
  #   key:
  #   value {
  #     stat_var:
  #   }
  # }
}

categories {
  title: "Health"
  blocks {
    columns {
      tiles {}
    }
  }
}

categories {
  title: "Shelter"
  blocks {
    columns {
      tiles {}
    }
  }
}

categories {
  title: "Economics"
  blocks {
    columns {
      tiles {}
    }
  }
}