# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import json

from flask import Response

# Header key used to identify responses generated by the recorder's fallback mechanism
FAKE_RESPONSE_HEADER = 'X-Webdriver-Fake-Response'


def _create_fake_response(data):
  return Response(json.dumps(data),
                  mimetype='application/json',
                  headers={FAKE_RESPONSE_HEADER: 'true'})


def _fake_place_name_response(request):
  req_json = request.get_json(silent=True) or {}
  dcids = req_json.get('dcids', [])
  return _create_fake_response({dcid: "" for dcid in dcids})


def _fake_variable_info_response(request):
  dcids = request.args.get('dcids', '').split(',')
  return _create_fake_response({dcid: {} for dcid in dcids if dcid})


def _fake_observation_response(request):
  return _create_fake_response({"data": {}, "facets": {}})


def _fake_place_parent_response(request):
  return _create_fake_response([])


def _fake_observation_existence_response(request):
  req_json = request.get_json(silent=True) or {}
  entities = req_json.get('entities', [])
  variables = req_json.get('variables', [])
  return _create_fake_response(
      {var: {
          entity: True for entity in entities
      } for var in variables})


def _fake_choropleth_geojson_response(request):
  return _create_fake_response({
      "type": "FeatureCollection",
      "features": [],
      "properties": {
          "current_geo": "06"
      }
  })


def _fake_facets_response(request):
  return _create_fake_response([])


def _fake_facets_within_response(request):
  return _create_fake_response({})


def _fake_node_propvals_out_response(request):
  return _create_fake_response({})


def _fake_node_triples_out_response(request):
  return _create_fake_response({})


def _fake_place_name_i18n_response(request):
  return _create_fake_response({})


def _fake_stat_var_property_response(request):
  return _create_fake_response({})


def _fake_variable_group_info_response(request):
  return _create_fake_response({
      "childStatVarGroups": [],
      "childStatVars": [],
      "descendentStatVarCount": 0
  })


def _fake_disaster_event_data_response(request):
  return _create_fake_response(
      {"eventCollection": {
          "events": [],
          "provenanceInfo": {}
      }})


# Register fallback responses
FALLBACK_RESPONSES = {
    '/api/place/name': _fake_place_name_response,
    '/api/place/displayname': _fake_place_name_response,
    '/api/place/parent': _fake_place_parent_response,
    '/api/observations/point': _fake_observation_response,
    '/api/observations/point/within': _fake_observation_response,
    '/api/observations/series': _fake_observation_response,
    '/api/variable/info': _fake_variable_info_response,
    '/api/variable-group/info': _fake_variable_group_info_response,
    '/api/observation/existence': _fake_observation_existence_response,
    '/api/choropleth/geojson': _fake_choropleth_geojson_response,
    '/api/facets': _fake_facets_response,
    '/api/facets/within': _fake_facets_within_response,
    '/api/node/propvals/out': _fake_node_propvals_out_response,
    '/api/place/name/i18n': _fake_place_name_i18n_response,
    '/api/stats/stat-var-property': _fake_stat_var_property_response,
    '/api/disaster-dashboard/event-data': _fake_disaster_event_data_response
}

# Prefix fallback responses
PREFIX_FALLBACK_RESPONSES = {
    '/api/node/triples/out/': _fake_node_triples_out_response
}
