# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stat_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stat_config.proto',
  package='datacommons.proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x11stat_config.proto\x12\x11\x64\x61tacommons.proto\"\xad\x02\n\nPopObsArgs\x12\x10\n\x08pop_type\x18\x01 \x01(\t\x12\r\n\x05mprop\x18\x02 \x01(\t\x12-\n\x03\x63pv\x18\x0e \x03(\x0b\x32 .datacommons.proto.PopObsSpec.PV\x12\x11\n\tstat_type\x18\x04 \x01(\t\x12\x0f\n\x07mmethod\x18\x05 \x01(\t\x12\x14\n\x0c\x64isplay_unit\x18\x06 \x01(\t\x12\x12\n\nobs_period\x18\x07 \x01(\t\x12\x17\n\x0flatest_obs_date\x18\x08 \x01(\t\x12\x11\n\tprov_hrid\x18\t \x01(\t\x12\r\n\x05title\x18\n \x01(\t\x12\x14\n\x0cmdenominator\x18\x0b \x01(\t\x12\x12\n\nmqualifier\x18\x0c \x01(\t\x12\x16\n\x0escaling_factor\x18\r \x01(\tJ\x04\x08\x03\x10\x04\"9\n\x0eProvenanceArgs\x12\x0c\n\x04hrid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\"m\n\x0ePopObsArgsList\x12*\n\x03\x61rg\x18\x01 \x03(\x0b\x32\x1d.datacommons.proto.PopObsArgs\x12/\n\x04prov\x18\x02 \x03(\x0b\x32!.datacommons.proto.ProvenanceArgs\"\xbf\x01\n\nPopObsSpec\x12\x10\n\x08pop_type\x18\x01 \x01(\t\x12\r\n\x05mprop\x18\x02 \x01(\t\x12\x11\n\tstat_type\x18\x03 \x01(\t\x12\r\n\x05\x63prop\x18\x04 \x03(\t\x12-\n\x03\x64pv\x18\x05 \x03(\x0b\x32 .datacommons.proto.PopObsSpec.PV\x12\x0c\n\x04name\x18\x06 \x01(\t\x12\x10\n\x08vertical\x18\x07 \x03(\t\x1a\x1f\n\x02PV\x12\x0c\n\x04prop\x18\x01 \x01(\t\x12\x0b\n\x03val\x18\x02 \x01(\t\"=\n\x0ePopObsSpecList\x12+\n\x04spec\x18\x01 \x03(\x0b\x32\x1d.datacommons.proto.PopObsSpec\"o\n\x13QuantityPropValSpec\x12\x10\n\x08pop_type\x18\x01 \x01(\t\x12\r\n\x05mprop\x18\x02 \x01(\t\x12\x11\n\tqty_cprop\x18\x03 \x01(\t\x12\x13\n\x0bother_cprop\x18\x04 \x03(\t\x12\x0f\n\x07qty_val\x18\x05 \x03(\t\"O\n\x17QuantityPropValSpecList\x12\x34\n\x04spec\x18\x01 \x03(\x0b\x32&.datacommons.proto.QuantityPropValSpec')
)




_POPOBSARGS = _descriptor.Descriptor(
  name='PopObsArgs',
  full_name='datacommons.proto.PopObsArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pop_type', full_name='datacommons.proto.PopObsArgs.pop_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mprop', full_name='datacommons.proto.PopObsArgs.mprop', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpv', full_name='datacommons.proto.PopObsArgs.cpv', index=2,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stat_type', full_name='datacommons.proto.PopObsArgs.stat_type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mmethod', full_name='datacommons.proto.PopObsArgs.mmethod', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='display_unit', full_name='datacommons.proto.PopObsArgs.display_unit', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='obs_period', full_name='datacommons.proto.PopObsArgs.obs_period', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latest_obs_date', full_name='datacommons.proto.PopObsArgs.latest_obs_date', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prov_hrid', full_name='datacommons.proto.PopObsArgs.prov_hrid', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='datacommons.proto.PopObsArgs.title', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mdenominator', full_name='datacommons.proto.PopObsArgs.mdenominator', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mqualifier', full_name='datacommons.proto.PopObsArgs.mqualifier', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scaling_factor', full_name='datacommons.proto.PopObsArgs.scaling_factor', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=342,
)


_PROVENANCEARGS = _descriptor.Descriptor(
  name='ProvenanceArgs',
  full_name='datacommons.proto.ProvenanceArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hrid', full_name='datacommons.proto.ProvenanceArgs.hrid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='datacommons.proto.ProvenanceArgs.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='datacommons.proto.ProvenanceArgs.url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=401,
)


_POPOBSARGSLIST = _descriptor.Descriptor(
  name='PopObsArgsList',
  full_name='datacommons.proto.PopObsArgsList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='arg', full_name='datacommons.proto.PopObsArgsList.arg', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prov', full_name='datacommons.proto.PopObsArgsList.prov', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=512,
)


_POPOBSSPEC_PV = _descriptor.Descriptor(
  name='PV',
  full_name='datacommons.proto.PopObsSpec.PV',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prop', full_name='datacommons.proto.PopObsSpec.PV.prop', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val', full_name='datacommons.proto.PopObsSpec.PV.val', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=675,
  serialized_end=706,
)

_POPOBSSPEC = _descriptor.Descriptor(
  name='PopObsSpec',
  full_name='datacommons.proto.PopObsSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pop_type', full_name='datacommons.proto.PopObsSpec.pop_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mprop', full_name='datacommons.proto.PopObsSpec.mprop', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stat_type', full_name='datacommons.proto.PopObsSpec.stat_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cprop', full_name='datacommons.proto.PopObsSpec.cprop', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dpv', full_name='datacommons.proto.PopObsSpec.dpv', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='datacommons.proto.PopObsSpec.name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vertical', full_name='datacommons.proto.PopObsSpec.vertical', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_POPOBSSPEC_PV, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=515,
  serialized_end=706,
)


_POPOBSSPECLIST = _descriptor.Descriptor(
  name='PopObsSpecList',
  full_name='datacommons.proto.PopObsSpecList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spec', full_name='datacommons.proto.PopObsSpecList.spec', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=708,
  serialized_end=769,
)


_QUANTITYPROPVALSPEC = _descriptor.Descriptor(
  name='QuantityPropValSpec',
  full_name='datacommons.proto.QuantityPropValSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pop_type', full_name='datacommons.proto.QuantityPropValSpec.pop_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mprop', full_name='datacommons.proto.QuantityPropValSpec.mprop', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qty_cprop', full_name='datacommons.proto.QuantityPropValSpec.qty_cprop', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='other_cprop', full_name='datacommons.proto.QuantityPropValSpec.other_cprop', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qty_val', full_name='datacommons.proto.QuantityPropValSpec.qty_val', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=771,
  serialized_end=882,
)


_QUANTITYPROPVALSPECLIST = _descriptor.Descriptor(
  name='QuantityPropValSpecList',
  full_name='datacommons.proto.QuantityPropValSpecList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spec', full_name='datacommons.proto.QuantityPropValSpecList.spec', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=884,
  serialized_end=963,
)

_POPOBSARGS.fields_by_name['cpv'].message_type = _POPOBSSPEC_PV
_POPOBSARGSLIST.fields_by_name['arg'].message_type = _POPOBSARGS
_POPOBSARGSLIST.fields_by_name['prov'].message_type = _PROVENANCEARGS
_POPOBSSPEC_PV.containing_type = _POPOBSSPEC
_POPOBSSPEC.fields_by_name['dpv'].message_type = _POPOBSSPEC_PV
_POPOBSSPECLIST.fields_by_name['spec'].message_type = _POPOBSSPEC
_QUANTITYPROPVALSPECLIST.fields_by_name['spec'].message_type = _QUANTITYPROPVALSPEC
DESCRIPTOR.message_types_by_name['PopObsArgs'] = _POPOBSARGS
DESCRIPTOR.message_types_by_name['ProvenanceArgs'] = _PROVENANCEARGS
DESCRIPTOR.message_types_by_name['PopObsArgsList'] = _POPOBSARGSLIST
DESCRIPTOR.message_types_by_name['PopObsSpec'] = _POPOBSSPEC
DESCRIPTOR.message_types_by_name['PopObsSpecList'] = _POPOBSSPECLIST
DESCRIPTOR.message_types_by_name['QuantityPropValSpec'] = _QUANTITYPROPVALSPEC
DESCRIPTOR.message_types_by_name['QuantityPropValSpecList'] = _QUANTITYPROPVALSPECLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PopObsArgs = _reflection.GeneratedProtocolMessageType('PopObsArgs', (_message.Message,), dict(
  DESCRIPTOR = _POPOBSARGS,
  __module__ = 'stat_config_pb2'
  # @@protoc_insertion_point(class_scope:datacommons.proto.PopObsArgs)
  ))
_sym_db.RegisterMessage(PopObsArgs)

ProvenanceArgs = _reflection.GeneratedProtocolMessageType('ProvenanceArgs', (_message.Message,), dict(
  DESCRIPTOR = _PROVENANCEARGS,
  __module__ = 'stat_config_pb2'
  # @@protoc_insertion_point(class_scope:datacommons.proto.ProvenanceArgs)
  ))
_sym_db.RegisterMessage(ProvenanceArgs)

PopObsArgsList = _reflection.GeneratedProtocolMessageType('PopObsArgsList', (_message.Message,), dict(
  DESCRIPTOR = _POPOBSARGSLIST,
  __module__ = 'stat_config_pb2'
  # @@protoc_insertion_point(class_scope:datacommons.proto.PopObsArgsList)
  ))
_sym_db.RegisterMessage(PopObsArgsList)

PopObsSpec = _reflection.GeneratedProtocolMessageType('PopObsSpec', (_message.Message,), dict(

  PV = _reflection.GeneratedProtocolMessageType('PV', (_message.Message,), dict(
    DESCRIPTOR = _POPOBSSPEC_PV,
    __module__ = 'stat_config_pb2'
    # @@protoc_insertion_point(class_scope:datacommons.proto.PopObsSpec.PV)
    ))
  ,
  DESCRIPTOR = _POPOBSSPEC,
  __module__ = 'stat_config_pb2'
  # @@protoc_insertion_point(class_scope:datacommons.proto.PopObsSpec)
  ))
_sym_db.RegisterMessage(PopObsSpec)
_sym_db.RegisterMessage(PopObsSpec.PV)

PopObsSpecList = _reflection.GeneratedProtocolMessageType('PopObsSpecList', (_message.Message,), dict(
  DESCRIPTOR = _POPOBSSPECLIST,
  __module__ = 'stat_config_pb2'
  # @@protoc_insertion_point(class_scope:datacommons.proto.PopObsSpecList)
  ))
_sym_db.RegisterMessage(PopObsSpecList)

QuantityPropValSpec = _reflection.GeneratedProtocolMessageType('QuantityPropValSpec', (_message.Message,), dict(
  DESCRIPTOR = _QUANTITYPROPVALSPEC,
  __module__ = 'stat_config_pb2'
  # @@protoc_insertion_point(class_scope:datacommons.proto.QuantityPropValSpec)
  ))
_sym_db.RegisterMessage(QuantityPropValSpec)

QuantityPropValSpecList = _reflection.GeneratedProtocolMessageType('QuantityPropValSpecList', (_message.Message,), dict(
  DESCRIPTOR = _QUANTITYPROPVALSPECLIST,
  __module__ = 'stat_config_pb2'
  # @@protoc_insertion_point(class_scope:datacommons.proto.QuantityPropValSpecList)
  ))
_sym_db.RegisterMessage(QuantityPropValSpecList)


# @@protoc_insertion_point(module_scope)
