runtime: python311

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
    expiration: "0d 0h"

  - url: /UNSDWebsite/static/(.*)
    static_files: build/static/\1
    upload: build/static/(.*)
    expiration: "0d 0h"

  - url: /UNSDWebsite/config/(.*)
    static_files: build/config/\1
    upload: build/config/(.*)
    expiration: "0d 0h"

  - url: /UNSDWebsite/images/(.*)
    static_files: build/images/\1
    upload: build/images/(.*)
    expiration: "0d 0h"

  - url: /UNSDWebsite/(.*)
    static_files: build/index.html
    upload: build/index.html
    expiration: "0d 0h"
