#Copyright (c) 2023 ONE Campaign

#This work is licensed under a Creative Commons Attribution 4.0 International License

## Topic page for africa

metadata {
  topic_id: "one-economy"
  topic_name: "Economy"
  place_dcid: "africa"
  contained_place_types {
    key: "Continent"
    value: "Country"
  }
}

### OVERVIEW ###
categories {
  title: "The basics"
  description: "Explore headline data on economic activity, including income distribution and the value of goods and services produced."

  # GINI Index
  blocks {
    title: "Income inequality"
    description: "The Gini Index measures income equality within an economy by looking at how income is distributed throughout the population. A higher Gini score means there is more inequality: a small number of individuals hold a higher share of income. A score of zero represents perfect income equality."
    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
          highest_title: "Highest Gini Index in Africa"
          lowest_title: "Lowest Gini Index in Africa"
        }
        stat_var_key: "GiniIndex_EconomicActivity"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "Income inequality (Gini Index ${date})"
        stat_var_key: "GiniIndex_EconomicActivity"
      }
    }
  }

  # GDP per capita
  blocks {
    title: "Gross domestic product (GDP) per capita"
    description: "GDP per capita measures the total value of the goods and services produced in a country by its population. It is used as a broad measure of the average living standard of a country; however, a high GDP per capita does not necessarily mean people have a higher standard of living."

    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "Amount_EconomicActivity_GrossDomesticProduction_Nominal_PerCapita"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "Nominal GDP Per Capita (${date})"
        stat_var_key: "Amount_EconomicActivity_GrossDomesticProduction_Nominal_PerCapita"
      }
    }
  }

  # GDP growth rate
  blocks {
    title: "Gross domestic product (GDP) growth rate"
    description: "The GDP growth rate measures how much a country’s economic output has grown or shrunk – essentially, an economy’s expansion or contraction during a specific period of time."

    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "GrowthRate_Amount_EconomicActivity_GrossDomesticProduction"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "Growth Rate of GDP (${date})"
        stat_var_key: "GrowthRate_Amount_EconomicActivity_GrossDomesticProduction"
      }
    }
  }

  # Inflation
  blocks {
    title: "Inflation rate"
    description: "Inflation rates tell you how much consumer prices have increased over a specified period of time. It is like a speedometer for prices: high inflation means your money buys you less than before and low inflation means prices are steady and your money retains its value."

    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "inflationPercentAverageConsumerPrices"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "Inflation (% average consumer prices) (${date})"
        stat_var_key: "inflationPercentAverageConsumerPrices"
      }
    }
  }

  ## Stat var spec overview section
  stat_var_spec {
    key: "GiniIndex_EconomicActivity"
    value {
      stat_var: "GiniIndex_EconomicActivity"
      name: "Gini Index"
    }
  }

  stat_var_spec {
    key: "Amount_EconomicActivity_GrossDomesticProduction_Nominal_PerCapita"
    value {
      stat_var: "Amount_EconomicActivity_GrossDomesticProduction_Nominal_PerCapita"
      name: "Nominal GDP Per Capita"
    }
  }

  stat_var_spec {
    key: "GrowthRate_Amount_EconomicActivity_GrossDomesticProduction"
    value {
      stat_var: "GrowthRate_Amount_EconomicActivity_GrossDomesticProduction"
      name: "Growth Rate of GDP"
    }
  }

  stat_var_spec {
    key: "inflationPercentAverageConsumerPrices"
    value {
      stat_var: "inflationPercentAverageConsumerPrices"
      name: "Inflation rate"
    }
  }
}

### DEBT ###
categories {
  title: "Data behind the debt"
  description: "Debt is an important source of financing to invest in a country’s economic and social development. But it has to be sustainable, meaning that governments must be able to reasonably pay it back. Explore the data behind Africa’s debt levels, including key factors that influence its sustainability."

  # PPG Debt Stocks
  blocks {
    title: "External Debt Stocks"
    description: "External long-term debt stocks show how much debt a country owes to external creditors. It’s often referred to as public or publicly guaranteed debt, meaning that it is owed by the government (and not accumulated by a household or private company)."

    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "AmountOutstanding_Debt_PubliclyGuaranteed_LongTermExternalDebt"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "External debt (PPG ${date})"
        stat_var_key: "AmountOutstanding_Debt_PubliclyGuaranteed_LongTermExternalDebt"
      }
    }
  }

  # PPG interest and principal repayments
  blocks {
    title: "Debt service on African governments’ external debt in the latest year"
    description:""

    columns {
      tiles {
        type: MAP
        title: "Interest payments to all external lenders (${date})"
        subtitle: "As with most loans, governments typically accrue interest on their debt. Interest rates on private loans or bonds are generally far higher than interest rates on loans from other governments. High interest rates can undermine debt sustainability, especially during crises."
        stat_var_key: "AmountInterestRepayment_Debt_PubliclyGuaranteed_LongTermExternalDebt"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "Principal payments to all external lenders (${date})"
        subtitle: "Principal repayments are the portion of the original loan amount paid during a period of time. The terms of a loan determine how frequently it is paid down, but most measures analyse yearly payments."
        stat_var_key: "AmountPrincipalRepayment_Debt_PubliclyGuaranteed_LongTermExternalDebt"
      }
    }
  }

  # Debt held in USD
  blocks {
    title: "External Debt held in US dollars"
    description: "A high proportion of African debt is denominated in US dollars. When the US Federal Reserve increases interest rates, this has the effect of strengthening the US dollar globally, which has an unfortunate knock on effect of devaluing other currencies, and thus driving up the cost of African debt in relation. When exacerbated, this dynamic can make debt levels skyrocket in real terms."

    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "Amount_Debt_USD_AsAFractionOf_Amount_Debt"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "Share of external debt held in US dollars (${date})"
        stat_var_key: "Amount_Debt_USD_AsAFractionOf_Amount_Debt"
      }
    }
  }

  stat_var_spec {
    key: "AmountOutstanding_Debt_PubliclyGuaranteed_LongTermExternalDebt"
    value {
      stat_var: "AmountOutstanding_Debt_PubliclyGuaranteed_LongTermExternalDebt"
      name: "External (long-term) debt stocks (PPG)"
    }
  }

  stat_var_spec {
    key: "AmountInterestRepayment_Debt_PubliclyGuaranteed_LongTermExternalDebt"
    value {
      stat_var: "AmountInterestRepayment_Debt_PubliclyGuaranteed_LongTermExternalDebt"
      name: "Interest payments to all external lenders"
      date: "2023"
    }
  }

  stat_var_spec {
    key: "AmountPrincipalRepayment_Debt_PubliclyGuaranteed_LongTermExternalDebt"
    value {
      stat_var: "AmountPrincipalRepayment_Debt_PubliclyGuaranteed_LongTermExternalDebt"
      name: "Principal payments to all external lenders"
      date: "2023"
    }
  }

  stat_var_spec {
    key: "Amount_Debt_EUR_AsAFractionOf_Amount_Debt"
    value {
      stat_var: "Amount_Debt_EUR_AsAFractionOf_Amount_Debt"
      name: "Share of external debt held in Euros"
    }
  }

  stat_var_spec {
    key: "Amount_Debt_GBP_AsAFractionOf_Amount_Debt"
    value {
      stat_var: "Amount_Debt_GBP_AsAFractionOf_Amount_Debt"
      name: "Share of external debt held in British Pounds"
    }
  }

  stat_var_spec {
    key: "Amount_Debt_USD_AsAFractionOf_Amount_Debt"
    value {
      stat_var: "Amount_Debt_USD_AsAFractionOf_Amount_Debt"
      name: "Share of external debt held in US dollars"
    }
  }

  stat_var_spec {
    key: "Amount_Debt_USD_AsAFractionOf_Amount_Debt"
    value {
      stat_var: "Amount_Debt_USD_AsAFractionOf_Amount_Debt"
      name: "Share of external debt held in US dollars"
    }
  }

}


### AID ###
categories {
  title: "Aid flows"
  description: "Official Development Assistance (ODA) or “global aid” is a transfer of money and resources from predominantly richer countries to low-income countries to help fight poverty and support economic development. Official aid is from government sources or international institutions, and does not include private aid."

  # Net aid received
  blocks {
    title: "Total aid received per country"
    description: "Net aid to African countries takes the total amount of official development assistance, minus any loans paid back. This includes aid directly from governments, as well as through multilateral institutions, like the Global Fund for AIDS, TB and Malaria."

    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "worldBank/DT_ODA_ALLD_CD"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "Net aid received (current US$) (${date})"
        stat_var_key: "worldBank/DT_ODA_ALLD_CD"
      }
    }
  }

  stat_var_spec {
    key: "worldBank/DT_ODA_ALLD_CD"
    value {
      stat_var: "worldBank/DT_ODA_ALLD_CD"
      name: "Net ODA (current US$)"
    }
  }
}

### REMITTANCES ###
categories {
  title: "Remittances"
  description: "Remittances are money or goods that migrants send back to families and friends in origin countries. They are often the most direct and well-known link between migration and development, and can be a lifeline in times of crisis. The level of remittances to African countries can surpass the amount of funds received through official aid or foreign investments."

  # Remittances received as a percent of GDP
  blocks {
    title: "Remittances received as a percent of GDP"
    description: "Remittances received as a percent of GDP measures the money or goods received by one household from someone living in another country, as a proportion of the country’s gross domestic product. This helps illustrate how reliant a country’s economy is on external sources of income."

    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "Amount_Remittance_InwardRemittance"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "Inward Remittances (${date})"
        stat_var_key: "Amount_Remittance_InwardRemittance"
      }
    }
  }

  # Remittances sent as a percent of GDP
  blocks {
    title: "Remittances sent as a percent of GDP"
    description: "Remittances sent as a percent of GDP measures the money or goods sent by one household to someone living in another country, as a proportion of the country’s gross domestic product."

    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "Amount_Remittance_OutwardRemittance"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "Remittances sent (${date})"
        stat_var_key: "Amount_Remittance_OutwardRemittance"
      }
    }
  }

  stat_var_spec {
    key: "Amount_Remittance_InwardRemittance"
    value {
      stat_var: "Amount_Remittance_InwardRemittance"
      name: "Remittances received"
    }
  }

  stat_var_spec {
    key: "Amount_Remittance_OutwardRemittance"
    value {
      stat_var: "Amount_Remittance_OutwardRemittance"
      name: "Remittances sent"
    }
  }
}

### SPECIAL DRAWING RIGHTS ###
categories {
  title: "Special Drawing Rights"
  description: "Special Drawing Rights (SDRs) are a reserve asset issued by the International Monetary Fund (IMF) to all its members. They are not cash, but they can be traded for hard currency if countries need to use them. In times of crisis, SDRs can  provide a much needed injection of liquidity to shore up reserves, stabilise currencies, meet external debt obligations, or address other pressing needs.\n\nA country’s relative size in the global economy determines how much it receives — so richer countries get the lion’s share. The most recent SDR allocation equivalent to $650 billion took place in August 2021 to help countries respond to the COVID-19 pandemic."

  # Allocations
  blocks {
    title: "SDR allocations"
    description: "SDR allocations to African countries measures the total amount of SDRs that have been distributed to these IMF members over time."

    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "SdrAllocationsSdr"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "SDR Allocations (${date})"
        stat_var_key: "SdrAllocationsSdr"
      }
    }
  }

  # Holdings
  blocks {
    title: "SDR Holdings"
    description: " SDR holdings of African countries measures the total amount of SDRs that are currently retained, i.e. haven’t been used, by these IMF members."

    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "SdrHoldingsSdr"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "Holdings (SDRs) (${date})"
        stat_var_key: "SdrHoldingsSdr"
      }
    }
  }

  stat_var_spec {
    key: "SdrAllocationsSdr"
    value {
      stat_var: "SdrAllocationsSdr"
      name: "Allocations (SDRs)"
    }
  }

  stat_var_spec {
    key: "SdrHoldingsSdr"
    value {
      stat_var: "SdrHoldingsSdr"
      name: "Holdings (SDRs)"
    }
  }
}