############################## ProvenanceArgs ##################################

prov: {
  hrid: "USCensus"
  name: "US Census"
  url: "https://www.census.gov"
}
prov: {
  hrid: "BLS"
  name: "US Bureau of Labor Statistics"
  url: "https://www.bls.gov"
}
prov: {
  hrid: "CDCMortality"
  name: "Centers for Disease Control and Prevention"
  url: "https://www.cdc.gov"
}
prov: {
  hrid: "CDC500"
  name: "Centers for Disease Control and Prevention"
  url: "https://www.cdc.gov"
}
prov: {
  hrid: "FBI"
  name: "FBI Uniform Crime Reporting"
  url: "https://www.fbi.gov/services/cjis/ucr"
}
prov: {
  hrid: "SEDA"
  name: "Stanford Educational Data Archive"
  url: "https://cepa.stanford.edu/seda/download?nid=2016&destination=node/2021"
}
prov: {
  hrid: "NCES"
  name: "National Center for Education Studies"
  url: "https://nces.ed.gov"
}
prov: {
  hrid: "DartmouthAtlas"
  name: "Dartmouth Atlas Data"
  url: "https://atlasdata.dartmouth.edu/static/general_atlas_rates"
}
prov: {
  hrid: "DEA_ARCOS"
  name: "US DEA Diversion Control Division"
  url: "https://www.deadiversion.usdoj.gov/arcos"
}
prov: {
  hrid: "USGSDisaster"
  name: "United states Geological Survey"
  url: "https://earthquake.usgs.gov"
}
prov: {
  hrid: "NOAADisaster"
  name: "National Climatic Data Center"
  url: "https://www.ncdc.noaa.gov"
}
prov: {
  hrid: "NatFAM"
  name: "National Fire and Aviation Management"
  url: "https://fam.nwcg.gov/fam-web"
}
prov: {
  hrid: "WDI"
  name: "World Development Indicators"
  url: "https://datacatalog.worldbank.org/dataset/world-development-indicators"
}
prov: {
  hrid: "Google"
  name: "Google"
  url: "http://google.com/"
}
prov: {
  hrid: "NYT"
  name: "New York Times"
  url: "http://nytimes.com/"
}
prov: {
  hrid: "USDOL_ETA539"
  name: "US Department of Labor"
  url: "http://doleta.gov/"
}

################################ PopObsArgs ####################################

## Census data ##

# General Population from census.
arg: {
  pop_type: "Person"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  mmethod: "CensusACS5yrSurvey"
  latest_obs_date: "2018"
  prov_hrid: "USCensus"
  title: "Population"
}
# Pop from Census SAHIE
arg: {
  pop_type: "Person"
  mprop: "count"
  cpv: {
    prop: "healthInsurance"
  }
  cpv: {
    prop: "age"
  }
  stat_type: "measuredValue"
  obs_period: "P1Y"
  latest_obs_date: "2017"
  prov_hrid: "USCensus"
  title: "Population"
}
arg: {
  pop_type: "Person"
  mprop: "count"
  cpv: {
    prop: "healthInsurance"
  }
  cpv: {
    prop: "race"
  }
  cpv: {
    prop: "age"
  }
  stat_type: "measuredValue"
  obs_period: "P1Y"
  latest_obs_date: "2017"
  prov_hrid: "USCensus"
  title: "Population"
}
arg: {
  pop_type: "Person"
  mprop: "count"
  cpv: {
    prop: "healthInsurance"
  }
  cpv: {
    prop: "race"
  }
  cpv: {
    prop: "age"
  }
  cpv: {
    prop: "gender"
  }
  stat_type: "measuredValue"
  obs_period: "P1Y"
  latest_obs_date: "2017"
  prov_hrid: "USCensus"
  title: "Population"
}
# Median Income from census.
arg: {
  pop_type: "Person"
  mprop: "income"
  cpv: {
    prop: "*"
  }
  stat_type: "medianValue"
  mmethod: "CensusACS5yrSurvey"
  latest_obs_date: "2018"
  prov_hrid: "USCensus"
  title: "Median Income"
  display_unit: "USD"
}
# Median Age from census.
arg: {
  pop_type: "Person"
  mprop: "age"
  cpv: {
    prop: "*"
  }
  stat_type: "medianValue"
  mmethod: "CensusACS5yrSurvey"
  latest_obs_date: "2018"
  prov_hrid: "USCensus"
  title: "Median Age"
  display_unit: "Years"
}
# Households
arg: {
  pop_type: "Household"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  mmethod: "CensusACS5yrSurvey"
  latest_obs_date: "2018"
  prov_hrid: "USCensus"
  title: "Number of Households"
}
# HousingUnit
arg: {
  pop_type: "HousingUnit"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  mmethod: "CensusACS5yrSurvey"
  latest_obs_date: "2018"
  prov_hrid: "USCensus"
  title: "Number of Houses"
}
# Establishment from Census CBP
arg: {
  pop_type: "USCEstablishment"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  mmethod: "CensusCBPSurvey"
  latest_obs_date: "2016"
  prov_hrid: "USCensus"
  title: "Number of Establishments"
}
arg: {
  pop_type: "USCEstablishment"
  mprop: "wagesAnnual"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  mmethod: "CensusCBPSurvey"
  latest_obs_date: "2016"
  prov_hrid: "USCensus"
  title: "Annual Wages of Establishments"
}
# Worker from Census CBP
arg: {
  pop_type: "USCWorker"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2016"
  obs_period: "P1Y"
  prov_hrid: "USCensus"
  title: "Number of Workers"
}

## BLS data ##

# Population by employment
arg: {
  pop_type: "Person"
  mprop: "count"
  cpv: {
    prop: "employment"
  }
  stat_type: "measuredValue"
  mmethod: "BLSSeasonallyUnadjusted"
  latest_obs_date: "2017"
  obs_period: "P1Y"
  prov_hrid: "BLS"
  title: "Population"
}
arg: {
  pop_type: "Person"
  mprop: "count"
  cpv: {
    prop: "employmentStatus"
  }
  stat_type: "measuredValue"
  mmethod: "BLSSeasonallyUnadjusted"
  latest_obs_date: "2018"
  obs_period: "P1Y"
  prov_hrid: "BLS"
  title: "Population"
}
# Unemployment rate.
arg: {
  pop_type: "Person"
  mprop: "unemploymentRate"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  mmethod: "BLSSeasonallyUnadjusted"
  latest_obs_date: "2017"
  obs_period: "P1Y"
  prov_hrid: "BLS"
  title: "Unemployment Rate"
  display_unit: "%"
}
# BLSEstablishment
arg: {
  pop_type: "BLSEstablishment"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2017"
  obs_period: "P1Y"
  prov_hrid: "BLS"
  title: "Number of Establishments"
}
# BLSWorker
arg: {
  pop_type: "BLSWorker"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2017"
  obs_period: "P1Y"
  prov_hrid: "BLS"
  title: "Number of Workers"
}
arg: {
  pop_type: "BLSWorker"
  mprop: "wagesAnnual"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2017"
  obs_period: "P1Y"
  prov_hrid: "BLS"
  title: "Annual Wages"
  display_unit: "USD"
}
arg: {
  pop_type: "BLSWorker"
  mprop: "wagesTotal"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2017"
  obs_period: "P1Y"
  prov_hrid: "BLS"
  title: "Total Wages"
  display_unit: "USD"
}
arg: {
  pop_type: "BLSWorker"
  mprop: "wagesWeekly"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2017"
  obs_period: "P1Y"
  prov_hrid: "BLS"
  title: "Weekly Wages"
  display_unit: "USD"
}

## FBI Crime Data ##

arg: {
  pop_type: "CriminalActivities"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2017"
  obs_period: "P1Y"
  prov_hrid: "FBI"
  title: "Number of Crimes"
}

## CDC Data ##

# CDC Wonder Mortality
arg: {
  pop_type: "MortalityEvent"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2017"
  obs_period: "P1Y"
  prov_hrid: "CDCMortality"
  title: "Mortality"
}
# CDC 500 Cities
arg: {
  pop_type: "Person"
  mprop: "percent"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  # Note: we prefer age-adjusted prevalence to crude, since that makes
  #       the comparison across places fairer.
  mmethod: "AgeAdjustedPrevalence"
  latest_obs_date: "2016"
  obs_period: "P1Y"
  prov_hrid: "CDC500"
  title: "Prevalence of Health Conditions"
  display_unit: "%"
}

## DEA Drug Data ##

arg: {
  pop_type: "DrugDistribution"
  mprop: "retailDrugDistribution"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2017-10"
  obs_period: "P3M"
  prov_hrid: "DEA_ARCOS"
  title: "Drug Distribution"
}

arg: {
  pop_type: "Student"
  mprop: "cohortScaleAchievement"
  cpv: {
    prop: "*"
  }
  stat_type: "meanValue"
  mmethod: "EmpiricalBayes"
  latest_obs_date: "2009"
  obs_period: "P6Y"
  prov_hrid: "SEDA"
  title: "Cohort Scale Achievement"
}
arg: {
  pop_type: "Student"
  mprop: "gradeCohortScaleAchievement"
  cpv: {
    prop: "*"
  }
  stat_type: "meanValue"
  mmethod: "EmpiricalBayes"
  latest_obs_date: "2009"
  obs_period: "P6Y"
  prov_hrid: "SEDA"
  title: "Grade Cohort Scale Achievement"
}
arg: {
  pop_type: "Student"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2015"
  prov_hrid: "SEDA"
  title: "Number of Students"
}
arg: {
  pop_type: "Student"
  mprop: "percent"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2015"
  prov_hrid: "SEDA"
  title: "Percent of Students"
  display_unit: "%"
}
arg: {
  pop_type: "Student"
  mprop: "naepTestScoreScaleAchievement"
  cpv: {
    prop: "*"
  }
  stat_type: "meanValue"
  latest_obs_date: "2015"
  prov_hrid: "SEDA"
  title: "NAEP Test Score Scale Achievement"
}
arg: {
  pop_type: "Student"
  mprop: "stateReferencedAchievement"
  cpv: {
    prop: "*"
  }
  stat_type: "meanValue"
  latest_obs_date: "2015"
  prov_hrid: "SEDA"
  title: "State Referenced Achievement"
}
arg: {
  pop_type: "Student"
  mprop: "studentTeacherRatio"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2016"
  prov_hrid: "NCES"
  title: "Student to Teacher Ratio"
}

## Dartmouth Atlas ##
## NOTE: This needs to be cleaned up when schema is redone.

arg: {
  pop_type: "MedicalProcedure"
  mprop: "count"
  cpv: {
    prop: "medicalCode"
  }
  cpv: {
    prop: "patientRace"
  }
  stat_type: "meanValue"
  latest_obs_date: "2014"
  obs_period: "P5Y"
  prov_hrid: "DartmouthAtlas"
  title: "Number of Medical Procedures"
}
arg: {
  pop_type: "MedicalProcedure"
  mprop: "count"
  cpv: {
    prop: "medicalEventEnum"
  }
  cpv: {
    prop: "patientRace"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2014"
  obs_period: "P5Y"
  prov_hrid: "DartmouthAtlas"
  title: "Number of Medical Procedures"
}
arg: {
  pop_type: "MedicalEnrollee"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2014"
  obs_period: "P1Y"
  prov_hrid: "DartmouthAtlas"
  title: "Number of Medical Enrollees"
}
arg: {
  pop_type: "MortalityEvent"
  mprop: "count"
  cpv: {
    prop: "medicareType"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2015"
  obs_period: "P1Y"
  prov_hrid: "DartmouthAtlas"
  title: "Number of Deaths"
}

### Disasters ###
arg: {
  pop_type: "CycloneEvent"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2019"
  prov_hrid: "NOAADisaster"
  title: "Number of Cyclone Events"
}
arg: {
  pop_type: "DroughtEvent"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2006"
  prov_hrid: "NOAADisaster"
  title: "Number of Drought Events"
}
arg: {
  pop_type: "EarthquakeEvent"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2019"
  prov_hrid: "USGSDisaster"
  title: "Number of Earthquakes"
}
arg: {
  pop_type: "FloodEvent"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2019"
  prov_hrid: "NOAADisaster"
  title: "Number of Flood Events"
}
arg: {
  pop_type: "FlashFloodEvent"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2019"
  prov_hrid: "NOAADisaster"
  title: "Number of Flash Flood Events"
}
arg: {
  pop_type: "ThunderstormWindEvent"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2019"
  prov_hrid: "NOAADisaster"
  title: "Number of Thunderstorms"
}
arg: {
  pop_type: "HailEvent"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2019"
  prov_hrid: "NOAADisaster"
  title: "Number of Hail Events"
}
arg: {
  pop_type: "HeavyRainEvent"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2019"
  prov_hrid: "NOAADisaster"
  title: "Number of Heavy Rain Events"
}
arg: {
  pop_type: "HeavySnowEvent"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2019"
  prov_hrid: "NOAADisaster"
  title: "Number of Heavy Snow Events"
}
arg: {
  pop_type: "HeatEvent"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2019"
  prov_hrid: "NOAADisaster"
  title: "Number of Heat Advisory Events"
}
arg: {
  pop_type: "TornadoEvent"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2019"
  prov_hrid: "NOAADisaster"
  title: "Number of Tornadoes"
}
arg: {
  pop_type: "WildlandFireEvent"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2018"
  prov_hrid: "NatFAM"
  title: "Number of Wildland Fires"
}

# WDI
# arg: {
#   pop_type: "Consumption"
#   mprop: "amount"
#   cpv: {
#     prop: "consumedThing"
#     val: "Energy"
#   }
#   stat_type: "measuredValue"
#   mdenominator: "PerCapita"
#   obs_period: "P1Y"
#   latest_obs_date: "2018"
#   prov_hrid: "WDI"
#   title: "Amount of Consumption"
#   display_unit: "KilogramOfOilEquivalent"
# }
# arg: {
#   pop_type: "Consumption"
#   mprop: "amount"
#   cpv: {
#     prop: "consumedThing"
#     val: "Electricity"
#   }
#   stat_type: "measuredValue"
#   mdenominator: "PerCapita"
#   obs_period: "P1Y"
#   latest_obs_date: "2018"
#   prov_hrid: "WDI"
#   title: "Amount of Consumption"
#   display_unit: "KilowattHour"
# }
# arg: {
#   pop_type: "EconomicActivity"
#   mprop: "amount"
#   cpv: {
#     prop: "activitySource"
#     val: "GrossDomesticProduction"
#   }
#   stat_type: "measuredValue"
#   mqualifier: "Nominal"
#   obs_period: "P1Y"
#   latest_obs_date: "2018"
#   prov_hrid: "WDI"
#   title: "Amount of Economic Activity"
# }
# arg: {
#   pop_type: "EconomicActivity"
#   mprop: "amount"
#   cpv: {
#     prop: "activitySource"
#     val: "GrossNationalIncome"
#   }
#   stat_type: "measuredValue"
#   mqualifier: "PurchasingPowerParity"
#   obs_period: "P1Y"
#   latest_obs_date: "2018"
#   prov_hrid: "WDI"
#   title: "Amount of Economic Activity"
# }
# # TODO(b/148618745): add mdenominator: "PerCapita" when bug fixed.
# # TODO(b/148618745): uncomment below once bug fixed.
# # arg: {
# #   pop_type: "EconomicActivity"
# #   mprop: "amount"
# #   cpv: {
# #     prop: "*"
# #   }
# #   stat_type: "growthRate"
# #   obs_period: "P1Y"
# #   latest_obs_date: "2018"
# #   prov_hrid: "WDI"
# #   title: "Growth Rate of Economic Activity"
# # }
# arg: {
#   pop_type: "Emissions"
#   mprop: "amount"
#   cpv: {
#     prop: "*"
#   }
#   stat_type: "measuredValue"
#   mdenominator: "PerCapita"
#   obs_period: "P1Y"
#   latest_obs_date: "2018"
#   prov_hrid: "WDI"
#   title: "Amount of Emissions"
# }
# # TODO(b/148618745): Support population and its growth rate once bug fixed.
# arg: {
#   pop_type: "Person"
#   mprop: "count"
#   cpv: {
#     prop: "isInternetUser"
#   }
#   stat_type: "measuredValue"
#   obs_period: "P1Y"
#   latest_obs_date: "2018"
#   prov_hrid: "WDI"
#   mdenominator: "PerCapita"
#   scaling_factor: "100"
#   title: "Number of Internet Users"
# }
# arg: {
#   pop_type: "Person"
#   mprop: "fertilityRate"
#   cpv: {
#     prop: "gender"
#   }
#   stat_type: "measuredValue"
#   latest_obs_date: "2017"
#   prov_hrid: "WDI"
#   title: "Fertility Rate"
# }
# arg: {
#   pop_type: "Person"
#   mprop: "lifeExpectancy"
#   cpv: {
#     prop: "*"
#   }
#   stat_type: "measuredValue"
#   latest_obs_date: "2017"
#   prov_hrid: "WDI"
#   title: "Life Expectancy"
# }

### MapFacts / GeoData Establishments ###
arg: {
  pop_type: "Park"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2020-02-18"
  prov_hrid: "Google"
  title: "Number of Parks"
}
arg: {
  pop_type: "Library"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2020-02-18"
  prov_hrid: "Google"
  title: "Number of Libraries"
}
arg: {
  pop_type: "ChildCare"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2020-02-18"
  prov_hrid: "Google"
  title: "Number of Child Cares"
}
arg: {
  pop_type: "Physician"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2020-02-18"
  prov_hrid: "Google"
  title: "Number of Physicians"
}
arg: {
  pop_type: "Pharmacy"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2020-02-18"
  prov_hrid: "Google"
  title: "Number of Pharmacies"
}
arg: {
  pop_type: "MedicalClinic"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2020-02-18"
  prov_hrid: "Google"
  title: "Number of Medical Clinics"
}
arg: {
  pop_type: "EmergencyRoom"
  mprop: "count"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  latest_obs_date: "2020-02-18"
  prov_hrid: "Google"
  title: "Number of Emergency Rooms"
}

### NYT COVID Data ###
arg: {
  pop_type: "MedicalConditionIncident"
  mprop: "cumulativeCount"
  cpv: {
    prop: "*"
  }
  stat_type: "measuredValue"
  mmethod: "NYT_COVID19_GitHub"
  latest_obs_date: "2020-03-28"
  prov_hrid: "NYT"
  title: "Medical Condition Incidents"
}
### US Dep of Labor Unemployment Insurance Claims Data ###
arg: {
  pop_type: "UnemploymentInsuranceClaim"
  mprop: "count"
  cpv: {
    prop: "benefitProgram"
    val: "StateUnemploymentInsurance"
  }
  stat_type: "measuredValue"
  mmethod: "BLSSeasonallyUnadjusted"
  latest_obs_date: "2020-03-28"
  obs_period: "P1W"
  prov_hrid: "USDOL_ETA539"
  title: "State Unemployment Insurance Claims"
}
arg: {
  pop_type: "UnemploymentInsuranceClaim"
  mprop: "count"
  cpv: {
    prop: "benefitProgram"
    val: "StateUnemploymentInsurance"
  }
  cpv: {
    prop: "claimType"
  }
  stat_type: "measuredValue"
  mmethod: "BLSSeasonallyUnadjusted"
  latest_obs_date: "2020-03-28"
  obs_period: "P1W"
  prov_hrid: "USDOL_ETA539"
  title: "State Unemployment Insurance Claims by Claim Type"
}
arg: {
  pop_type: "UnemploymentInsuranceClaim"
  mprop: "count"
  cpv: {
    prop: "benefitProgram"
    val: "UCFENoStateUnemploymentInsurance"
  }
  stat_type: "measuredValue"
  mmethod: "BLSSeasonallyUnadjusted"
  latest_obs_date: "2020-03-28"
  obs_period: "P1W"
  prov_hrid: "USDOL_ETA539"
  title: "Unemployment Compensation for Federal Employees Claims"
}
arg: {
  pop_type: "UnemploymentInsuranceClaim"
  mprop: "count"
  cpv: {
    prop: "benefitProgram"
    val: "UCFENoStateUnemploymentInsurance"
  }
  cpv: {
    prop: "claimType"
  }
  stat_type: "measuredValue"
  mmethod: "BLSSeasonallyUnadjusted"
  latest_obs_date: "2020-03-28"
  obs_period: "P1W"
  prov_hrid: "USDOL_ETA539"
  title: "Unemployment Compensation for Federal Employees Claims by Claim Type"
}
arg: {
  pop_type: "UnemploymentInsuranceClaim"
  mprop: "count"
  cpv: {
    prop: "benefitProgram"
    val: "UCXOnly"
  }
  stat_type: "measuredValue"
  mmethod: "BLSSeasonallyUnadjusted"
  latest_obs_date: "2020-03-28"
  obs_period: "P1W"
  prov_hrid: "USDOL_ETA539"
  title: "Unemployment Compensation for Ex-Servicemembers Claims"
}
arg: {
  pop_type: "UnemploymentInsuranceClaim"
  mprop: "count"
  cpv: {
    prop: "benefitProgram"
    val: "UCXOnly"
  }
  cpv: {
    prop: "claimType"
  }
  stat_type: "measuredValue"
  mmethod: "BLSSeasonallyUnadjusted"
  latest_obs_date: "2020-03-28"
  obs_period: "P1W"
  prov_hrid: "USDOL_ETA539"
  title: "Unemployment Compensation for Ex-Servicemembers Claims by Claim Type"
}
arg: {
  pop_type: "UnemploymentInsuranceClaim"
  mprop: "count"
  cpv: {
    prop: "benefitProgram"
    val: "ShortTimeCompensation"
  }
  stat_type: "measuredValue"
  mmethod: "BLSSeasonallyUnadjusted"
  mqualifier: "ScaledForPartTimeUnemploymentBenefits"
  latest_obs_date: "2020-03-28"
  obs_period: "P1W"
  prov_hrid: "USDOL_ETA539"
  title: "Workshare Benefit Claims"
}
arg: {
  pop_type: "UnemploymentInsuranceClaim"
  mprop: "count"
  cpv: {
    prop: "benefitProgram"
    val: "ShortTimeCompensation"
  }
  cpv: {
    prop: "claimType"
  }
  stat_type: "measuredValue"
  mmethod: "BLSSeasonallyUnadjusted"
  mqualifier: "ScaledForPartTimeUnemploymentBenefits"
  latest_obs_date: "2020-03-28"
  obs_period: "P1W"
  prov_hrid: "USDOL_ETA539"
  title: "Workshare Benefit Claims by Claim Type"
}
arg: {
  pop_type: "UnemploymentInsuranceClaim"
  mprop: "count"
  cpv: {
    prop: "benefitProgram"
    val: "StateUnemploymentInsuranceOrShortTimeCompensation"
  }
  cpv: {
    prop: "claimType"
    val: "ContinuedClaim"
  }
  stat_type: "measuredValue"
  mmethod: "BLSSeasonallyUnadjusted"
  mqualifier: "MovingAverage1WeekWindow"
  latest_obs_date: "2020-03-28"
  obs_period: "P13W"
  prov_hrid: "USDOL_ETA539"
  title: "State Unemployment Insurance and Workshare Claims (13 Week Moving Avg)"
}
arg: {
  pop_type: "Person"
  mprop: "insuredUnemploymentRate"
  cpv: {
    prop: "unemploymentInsuranceStatus"
  }
  stat_type: "measuredValue"
  mmethod: "BLSSeasonallyUnadjusted"
  mqualifier: "MovingAverage1WeekWindow"
  latest_obs_date: "2020-03-28"
  obs_period: "P13W"
  prov_hrid: "USDOL_ETA539"
  title: "Insured Unemployment Rate (13 Week Moving Avg)"
  display_unit: "%"
}
