/**
 * List of world countries and their DCIDs
 * TODO: Filter by 193 UN member states + 2 observers
 */
export const COUNTRIES = Object.freeze([
  { name: "Aruba", geoDcid: "country/ABW" },
  { name: "Afghanistan", geoDcid: "country/AFG" },
  { name: "Angola", geoDcid: "country/AGO" },
  { name: "Anguilla", geoDcid: "country/AIA" },
  { name: "Albania", geoDcid: "country/ALB" },
  { name: "Andorra", geoDcid: "country/AND" },
  { name: "United Arab Emirates", geoDcid: "country/ARE" },
  { name: "Argentina", geoDcid: "country/ARG" },
  { name: "Armenia", geoDcid: "country/ARM" },
  { name: "American Samoa", geoDcid: "country/ASM" },
  { name: "French Southern Territories", geoDcid: "country/ATF" },
  { name: "Antigua and Barbuda", geoDcid: "country/ATG" },
  { name: "Australia", geoDcid: "country/AUS" },
  { name: "Austria", geoDcid: "country/AUT" },
  { name: "Azerbaijan", geoDcid: "country/AZE" },
  { name: "Burundi", geoDcid: "country/BDI" },
  { name: "Belgium", geoDcid: "country/BEL" },
  { name: "Benin", geoDcid: "country/BEN" },
  { name: "Bonaire, Sint Eustatius and Saba", geoDcid: "country/BES" },
  { name: "Burkina Faso", geoDcid: "country/BFA" },
  { name: "Bangladesh", geoDcid: "country/BGD" },
  { name: "Bulgaria", geoDcid: "country/BGR" },
  { name: "Bahrain", geoDcid: "country/BHR" },
  { name: "Bahamas", geoDcid: "country/BHS" },
  { name: "Bosnia and Herzegovina", geoDcid: "country/BIH" },
  { name: "Saint Barthélemy", geoDcid: "country/BLM" },
  { name: "Belarus", geoDcid: "country/BLR" },
  { name: "Belize", geoDcid: "country/BLZ" },
  { name: "Bermuda", geoDcid: "country/BMU" },
  { name: "Bolivia", geoDcid: "country/BOL" },
  { name: "Brazil", geoDcid: "country/BRA" },
  { name: "Barbados", geoDcid: "country/BRB" },
  { name: "Brunei", geoDcid: "country/BRN" },
  { name: "Bhutan", geoDcid: "country/BTN" },
  { name: "Botswana", geoDcid: "country/BWA" },
  { name: "Central African Republic", geoDcid: "country/CAF" },
  { name: "Canada", geoDcid: "country/CAN" },
  { name: "Cocos (Keeling) Islands", geoDcid: "country/CCK" },
  { name: "Switzerland", geoDcid: "country/CHE" },
  { name: "Chile", geoDcid: "country/CHL" },
  { name: "People's Republic of China", geoDcid: "country/CHN" },
  { name: "Ivory Coast", geoDcid: "country/CIV" },
  { name: "Cameroon", geoDcid: "country/CMR" },
  { name: "Congo [DRC]", geoDcid: "country/COD" },
  { name: "Republic of the Congo", geoDcid: "country/COG" },
  { name: "Cook Islands", geoDcid: "country/COK" },
  { name: "Colombia", geoDcid: "country/COL" },
  { name: "Comoros", geoDcid: "country/COM" },
  { name: "Cape Verde", geoDcid: "country/CPV" },
  { name: "Costa Rica", geoDcid: "country/CRI" },
  { name: "Cuba", geoDcid: "country/CUB" },
  { name: "Curaçao", geoDcid: "country/CUW" },
  { name: "Christmas Island", geoDcid: "country/CXR" },
  { name: "Cayman Islands", geoDcid: "country/CYM" },
  { name: "Republic of Cyprus", geoDcid: "country/CYP" },
  { name: "Czech Republic", geoDcid: "country/CZE" },
  { name: "Germany", geoDcid: "country/DEU" },
  { name: "Djibouti", geoDcid: "country/DJI" },
  { name: "Dominica", geoDcid: "country/DMA" },
  { name: "Denmark", geoDcid: "country/DNK" },
  { name: "Dominican Republic", geoDcid: "country/DOM" },
  { name: "Algeria", geoDcid: "country/DZA" },
  { name: "Ecuador", geoDcid: "country/ECU" },
  { name: "Egypt", geoDcid: "country/EGY" },
  { name: "Eritrea", geoDcid: "country/ERI" },
  { name: "Spain", geoDcid: "country/ESP" },
  { name: "Estonia", geoDcid: "country/EST" },
  { name: "Ethiopia", geoDcid: "country/ETH" },
  { name: "Finland", geoDcid: "country/FIN" },
  { name: "Fiji", geoDcid: "country/FJI" },
  { name: "Falkland Islands", geoDcid: "country/FLK" },
  { name: "France", geoDcid: "country/FRA" },
  { name: "Faroe Islands", geoDcid: "country/FRO" },
  { name: "Federated States of Micronesia", geoDcid: "country/FSM" },
  { name: "Gabon", geoDcid: "country/GAB" },
  { name: "United Kingdom", geoDcid: "country/GBR" },
  { name: "Georgia", geoDcid: "country/GEO" },
  { name: "Guernsey", geoDcid: "country/GGY" },
  { name: "Ghana", geoDcid: "country/GHA" },
  { name: "Gibraltar", geoDcid: "country/GIB" },
  { name: "Guinea", geoDcid: "country/GIN" },
  { name: "Gambia", geoDcid: "country/GMB" },
  { name: "Guinea-Bissau", geoDcid: "country/GNB" },
  { name: "Equatorial Guinea", geoDcid: "country/GNQ" },
  { name: "Greece", geoDcid: "country/GRC" },
  { name: "Grenada", geoDcid: "country/GRD" },
  { name: "Greenland", geoDcid: "country/GRL" },
  { name: "Guatemala", geoDcid: "country/GTM" },
  { name: "Guam", geoDcid: "country/GUM" },
  { name: "Guyana", geoDcid: "country/GUY" },
  { name: "Hong Kong", geoDcid: "country/HKG" },
  { name: "Heard Island and McDonald Islands", geoDcid: "country/HMD" },
  { name: "Honduras", geoDcid: "country/HND" },
  { name: "Croatia", geoDcid: "country/HRV" },
  { name: "Haiti", geoDcid: "country/HTI" },
  { name: "Hungary", geoDcid: "country/HUN" },
  { name: "Indonesia", geoDcid: "country/IDN" },
  { name: "Isle of Man", geoDcid: "country/IMN" },
  { name: "India", geoDcid: "country/IND" },
  { name: "British Indian Ocean Territory", geoDcid: "country/IOT" },
  { name: "Ireland", geoDcid: "country/IRL" },
  { name: "Iran", geoDcid: "country/IRN" },
  { name: "Iraq", geoDcid: "country/IRQ" },
  { name: "Iceland", geoDcid: "country/ISL" },
  { name: "Israel", geoDcid: "country/ISR" },
  { name: "Italy", geoDcid: "country/ITA" },
  { name: "Jamaica", geoDcid: "country/JAM" },
  { name: "Jersey", geoDcid: "country/JEY" },
  { name: "Jordan", geoDcid: "country/JOR" },
  { name: "Japan", geoDcid: "country/JPN" },
  { name: "Kazakhstan", geoDcid: "country/KAZ" },
  { name: "Kenya", geoDcid: "country/KEN" },
  { name: "Kyrgyzstan", geoDcid: "country/KGZ" },
  { name: "Cambodia", geoDcid: "country/KHM" },
  { name: "Kiribati", geoDcid: "country/KIR" },
  { name: "Saint Kitts and Nevis", geoDcid: "country/KNA" },
  { name: "South Korea", geoDcid: "country/KOR" },
  { name: "Kuwait", geoDcid: "country/KWT" },
  { name: "Laos", geoDcid: "country/LAO" },
  { name: "Lebanon", geoDcid: "country/LBN" },
  { name: "Liberia", geoDcid: "country/LBR" },
  { name: "Libya", geoDcid: "country/LBY" },
  { name: "Saint Lucia", geoDcid: "country/LCA" },
  { name: "Liechtenstein", geoDcid: "country/LIE" },
  { name: "Sri Lanka", geoDcid: "country/LKA" },
  { name: "Lesotho", geoDcid: "country/LSO" },
  { name: "Lithuania", geoDcid: "country/LTU" },
  { name: "Luxembourg", geoDcid: "country/LUX" },
  { name: "Latvia", geoDcid: "country/LVA" },
  { name: "Macau", geoDcid: "country/MAC" },
  { name: "Saint Martin (French part)", geoDcid: "country/MAF" },
  { name: "Morocco", geoDcid: "country/MAR" },
  { name: "Monaco", geoDcid: "country/MCO" },
  { name: "Moldova", geoDcid: "country/MDA" },
  { name: "Madagascar", geoDcid: "country/MDG" },
  { name: "Maldives", geoDcid: "country/MDV" },
  { name: "Mexico", geoDcid: "country/MEX" },
  { name: "Marshall Islands", geoDcid: "country/MHL" },
  { name: "North Macedonia", geoDcid: "country/MKD" },
  { name: "Mali", geoDcid: "country/MLI" },
  { name: "Malta", geoDcid: "country/MLT" },
  { name: "Myanmar", geoDcid: "country/MMR" },
  { name: "Montenegro", geoDcid: "country/MNE" },
  { name: "Mongolia", geoDcid: "country/MNG" },
  { name: "Northern Mariana Islands", geoDcid: "country/MNP" },
  { name: "Mozambique", geoDcid: "country/MOZ" },
  { name: "Mauritania", geoDcid: "country/MRT" },
  { name: "Montserrat", geoDcid: "country/MSR" },
  { name: "Mauritius", geoDcid: "country/MUS" },
  { name: "Malawi", geoDcid: "country/MWI" },
  { name: "Malaysia", geoDcid: "country/MYS" },
  { name: "Namibia", geoDcid: "country/NAM" },
  { name: "New Caledonia", geoDcid: "country/NCL" },
  { name: "Niger", geoDcid: "country/NER" },
  { name: "Norfolk Island", geoDcid: "country/NFK" },
  { name: "Nigeria", geoDcid: "country/NGA" },
  { name: "Nicaragua", geoDcid: "country/NIC" },
  { name: "Niue", geoDcid: "country/NIU" },
  { name: "Netherlands", geoDcid: "country/NLD" },
  { name: "Norway", geoDcid: "country/NOR" },
  { name: "Nepal", geoDcid: "country/NPL" },
  { name: "Nauru", geoDcid: "country/NRU" },
  { name: "New Zealand", geoDcid: "country/NZL" },
  { name: "Oman", geoDcid: "country/OMN" },
  { name: "Pakistan", geoDcid: "country/PAK" },
  { name: "Panama", geoDcid: "country/PAN" },
  { name: "Pitcairn Islands", geoDcid: "country/PCN" },
  { name: "Peru", geoDcid: "country/PER" },
  { name: "Philippines", geoDcid: "country/PHL" },
  { name: "Palau", geoDcid: "country/PLW" },
  { name: "Papua New Guinea", geoDcid: "country/PNG" },
  { name: "Poland", geoDcid: "country/POL" },
  { name: "Puerto Rico", geoDcid: "country/PRI" },
  { name: "North Korea", geoDcid: "country/PRK" },
  { name: "Portugal", geoDcid: "country/PRT" },
  { name: "Paraguay", geoDcid: "country/PRY" },
  { name: "State of Palestine", geoDcid: "country/PSE" },
  { name: "French Polynesia", geoDcid: "country/PYF" },
  { name: "Qatar", geoDcid: "country/QAT" },
  { name: "Romania", geoDcid: "country/ROU" },
  { name: "Russia", geoDcid: "country/RUS" },
  { name: "Rwanda", geoDcid: "country/RWA" },
  { name: "Saudi Arabia", geoDcid: "country/SAU" },
  { name: "Sudan", geoDcid: "country/SDN" },
  { name: "Senegal", geoDcid: "country/SEN" },
  { name: "Singapore", geoDcid: "country/SGP" },
  {
    name: "South Georgia and the South Sandwich Islands",
    geoDcid: "country/SGS",
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    geoDcid: "country/SHN",
  },
  { name: "Solomon Islands", geoDcid: "country/SLB" },
  { name: "Sierra Leone", geoDcid: "country/SLE" },
  { name: "El Salvador", geoDcid: "country/SLV" },
  { name: "San Marino", geoDcid: "country/SMR" },
  { name: "Somalia", geoDcid: "country/SOM" },
  { name: "Saint Pierre and Miquelon", geoDcid: "country/SPM" },
  { name: "Serbia", geoDcid: "country/SRB" },
  { name: "South Sudan", geoDcid: "country/SSD" },
  { name: "São Tomé and Príncipe", geoDcid: "country/STP" },
  { name: "Suriname", geoDcid: "country/SUR" },
  { name: "Slovakia", geoDcid: "country/SVK" },
  { name: "Slovenia", geoDcid: "country/SVN" },
  { name: "Sweden", geoDcid: "country/SWE" },
  { name: "Eswatini", geoDcid: "country/SWZ" },
  { name: "Sint Maarten (Dutch part)", geoDcid: "country/SXM" },
  { name: "Seychelles", geoDcid: "country/SYC" },
  { name: "Syria", geoDcid: "country/SYR" },
  { name: "Turks and Caicos Islands", geoDcid: "country/TCA" },
  { name: "Chad", geoDcid: "country/TCD" },
  { name: "Togo", geoDcid: "country/TGO" },
  { name: "Thailand", geoDcid: "country/THA" },
  { name: "Tajikistan", geoDcid: "country/TJK" },
  { name: "Tokelau", geoDcid: "country/TKL" },
  { name: "Turkmenistan", geoDcid: "country/TKM" },
  { name: "East Timor", geoDcid: "country/TLS" },
  { name: "Tonga", geoDcid: "country/TON" },
  { name: "Trinidad and Tobago", geoDcid: "country/TTO" },
  { name: "Tunisia", geoDcid: "country/TUN" },
  { name: "Turkey", geoDcid: "country/TUR" },
  { name: "Tuvalu", geoDcid: "country/TUV" },
  { name: "Tanzania", geoDcid: "country/TZA" },
  { name: "Uganda", geoDcid: "country/UGA" },
  { name: "Ukraine", geoDcid: "country/UKR" },
  { name: "United States Minor Outlying Islands", geoDcid: "country/UMI" },
  { name: "Uruguay", geoDcid: "country/URY" },
  { name: "United States of America", geoDcid: "country/USA" },
  { name: "Uzbekistan", geoDcid: "country/UZB" },
  { name: "Vatican City", geoDcid: "country/VAT" },
  { name: "Saint Vincent and the Grenadines", geoDcid: "country/VCT" },
  { name: "Venezuela", geoDcid: "country/VEN" },
  { name: "British Virgin Islands", geoDcid: "country/VGB" },
  { name: "United States Virgin Islands", geoDcid: "country/VIR" },
  { name: "Vietnam", geoDcid: "country/VNM" },
  { name: "Vanuatu", geoDcid: "country/VUT" },
  { name: "Wallis and Futuna", geoDcid: "country/WLF" },
  { name: "Samoa", geoDcid: "country/WSM" },
  { name: "Yemen", geoDcid: "country/YEM" },
  { name: "South Africa", geoDcid: "country/ZAF" },
  { name: "Zambia", geoDcid: "country/ZMB" },
  { name: "Zimbabwe", geoDcid: "country/ZWE" },
]);

/**
 * Country dcid lookup object. Key is geoDcid, value is country name
 *
 * Example:
 * {
 *   "country/FLK" : "Falkland Islands",
 *   "country/PRK" : "North Korea",
 *   "country/GRC" : "Greece",
 *   ...
 * }
 */
export const COUNTRY_DCID_LOOKUP: { [dcid: string]: string } = Object.freeze(
  Object.fromEntries(COUNTRIES.map((item) => [item.geoDcid, item.name]))
);
