# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## This file specifies the topic page config for poverty in USA

metadata {
  topic_id: "foodsecurity"
  topic_name: "Food Security"
  place_dcid: "geoId/06"
  contained_place_types {
    key: "State"
    value: "County"
  }
}

categories {
  title: "Health Conditions"
  description: "(Description of health conditions will go here)"
  blocks {
    title: "Prevalance of Diabetes"
    description: "(Prevalence of diabetes description will go here)"
    columns {
      tiles {
        type: MAP
        title: "Prevalence of diabetes (${date})"
        stat_var_key: "prevalence_diabetes"
      }
    }
    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "prevalence_diabetes"
      }
    }
  }

  blocks {
    title: "Health conditions"
    columns {
      tiles {
        type: BAR
        title: "Health conditions"
        stat_var_key: "prevalence_diabetes"
        stat_var_key: "prevalence_chd"
        stat_var_key: "prevalence_highbloodpressure"
        stat_var_key: "prevalence_highcholesterol"
      }
    }
    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          highest_title: "Highest among ${statVar}"
        }
        stat_var_key: "prevalence_diabetes"
        stat_var_key: "prevalence_chd"
        stat_var_key: "prevalence_highbloodpressure"
        stat_var_key: "prevalence_highcholesterol"
      }
    }
  }


  stat_var_spec {
    key: "prevalence_diabetes"
    value {
      stat_var: "Percent_Person_WithDiabetes"
      name: "Percentage of population with Diabetes"
    }
  }
  stat_var_spec {
    key: "prevalence_chd"
    value {
      stat_var: "Percent_Person_WithCoronaryHeartDisease"
      name: "Percentage of population with Coronary Heart Disease"
    }
  }
  stat_var_spec {
    key: "prevalence_highbloodpressure"
    value {
      stat_var: "Percent_Person_WithHighBloodPressure"
      name: "Percentage of population with High Blood Pressure"
    }
  }
  stat_var_spec {
    key: "prevalence_highcholesterol"
    value {
      stat_var: "Percent_Person_WithHighCholesterol"
      name: "Percentage of population with High Cholesterol"
    }
  }
}

