# Copyright 2023 ONE Campaign

## Test topic page for africa

metadata {
  topic_id: "one-health"
  topic_name: "Health"
  place_dcid: "africa"
  contained_place_types {
    key: "Continent"
    value: "Country"
  }
}


### OVERVIEW ###
categories {
  title: "The basics"
  description: "The health and well-being of a population begins in the womb. Data on maternal health, infant mortality, and life expectancy are a pulse check on the health of a country. Access to quality healthcare is one of the many factors that contributes to higher life expectancy and lower maternal and infant mortality rates."
  

  # Life Expectancy
  blocks {
    title: "Life Expectancy"
    description: "Life expectancy at birth indicates the average number of years a newborn could expect to live. This provides a snapshot of population health and mortality. High life expectancy is generally associated with good healthcare, nutrition, sanitation, and other socioeconomic conditions."
    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "LifeExpectancy_Person"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "Life Expectancy (${date})"
        stat_var_key: "LifeExpectancy_Person"
      }
    }
  }

  # Maternal Mortality
  blocks {
    title: "Maternal Mortality"
    description: "The number of mothers who die from complications during or following childbirth, measured per 100,000 live births. Maternal mortality is a critical indicator of the quality and accessibility of maternal healthcare services, including access to skilled birth attendants, amongst other things."
    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "WHO/MDG_0000000026"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "Maternal Mortality Ratio (Per 100 000 Live Births) (${date})"
        stat_var_key: "WHO/MDG_0000000026"
      }
    }
  }

  # Infant Mortality
  blocks {
    title: "Infant Mortality"
    description: "The likelihood of newborn infant deaths before the age of 1 year, per 1,000 live births. Infant mortality rate can be associated with access to healthcare, clean water, and sanitation as well as infectious diseases, malnutrition and vaccination coverage."
    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "sdg/SH_DYN_IMRT.AGE--Y0"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "Infant Mortality Rate (under 1 year old) (${date})"
        stat_var_key: "sdg/SH_DYN_IMRT.AGE--Y0"
      }
    }
  }

  
  stat_var_spec {
    key: "LifeExpectancy_Person"
    value {
      stat_var: "LifeExpectancy_Person"
      name: "Life Expectancy"
    }
  }

  stat_var_spec {
    key: "WHO/MDG_0000000026"
    value {
      stat_var: "WHO/MDG_0000000026"
      name: "Maternal Mortality Ratio (Per 100 000 Live Births)"
    }
  }

  stat_var_spec {
    key: "sdg/SH_DYN_IMRT.AGE--Y0"
    value {
      stat_var: "sdg/SH_DYN_IMRT.AGE--Y0"
      name: "Infant Mortality Rate (under 1 year old)"
    }
  }

}

### HEALTH FINANCING ###
categories {
  title: "Health financing"
  description: "Health financing is vital to functioning health systems. Strong health systems ensure that people can access quality health services and have their health needs addressed without suffering personal financial hardship. Total health spending has risen across all income levels over the past 20 years, but higher-income countries account for the majority of this spending. Individuals in low-income countries often have to pay for health expenses out-of-pocket, pushing millions into extreme poverty as a result."
  # Total Health Expenditure
  blocks {
    title: "Total health expenditure"
    description: "Health spending from all sources, including domestic government, external aid, domestic private, and out-of-pocket health spending."
    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "healthExpenditureCurrentUSD"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "Total health expenditure (current USD) (${date})"
        stat_var_key: "healthExpenditureCurrentUSD"
      }
    }
  }

  # Total Health Expenditure from external sources
  blocks {
    title: "Health expenditure from external sources"
    description: "Measures the amount of external funding channelled into a country’s national health system. These transfers can be distributed directly to a hospital or clinic, or sent to a recipient government and then distributed."
    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "healthExpenditureExternalCurrentUSD"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "Health expenditure from external sources (current USD) (${date})"
        stat_var_key: "healthExpenditureExternalCurrentUSD"
      }
    }
  }

  # Out-of-pocket health expenditure
  blocks {
    title: "Out-of-pocket health expenditure"
    description: "Measures how much people are directly paying for their healthcare. In many countries, self- or family-reliance for healthcare can push families into debt."
    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "healthExpenditureFinancingSchemeOopCurrentUSD"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "Out-of-pocket health expenditure (current USD) (${date})"
        stat_var_key: "healthExpenditureFinancingSchemeOopCurrentUSD"
      }
    }
  }

  stat_var_spec {
    key: "healthExpenditureCurrentUSD"
    value {
      stat_var: "healthExpenditureCurrentUSD"
      name: "Total health expenditure (current USD)"
    }
  }

  stat_var_spec {
    key: "healthExpenditureExternalCurrentUSD"
    value {
      stat_var: "healthExpenditureExternalCurrentUSD"
      name: "Health expenditure from external sources (current USD)"
    }
  }

  stat_var_spec {
    key: "healthExpenditureFinancingSchemeOopCurrentUSD"
    value {
      stat_var: "healthExpenditureFinancingSchemeOopCurrentUSD"
      name: "Out-of-pocket health expenditure (current USD)"
    }
  }

}


### PREVENTABLE INFECTIOUS DISEASES ###
categories {
  title: "Preventable infectious diseases"
  description: "Infectious diseases, such as HIV, tuberculosis and malaria, are amongst the leading causes of death in the world’s most vulnerable countries, despite being completely preventable or treatable. Ensuring equitable access to life-saving health services and medicines, including vaccines, has the potential to save lives now, increase life expectancy over time, and disrupt the cycle of poverty."

  # HIV New infections
  blocks {
    title: "New HIV infections"
    description: "The human immunodeficiency virus (HIV) targets cells in the immune system – the body’s defence against illness – and weakens the body’s ability to fight against infections and some types of cancer. This indicator measures the number of recorded cases of new HIV infections, so its accuracy is dependent on robust health systems."
    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "HivNewInfectionsPeople"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "New HIV infections (number of people) (${date})"
        stat_var_key: "HivNewInfectionsPeople"
      }
    }
  }

  # AIDS related deaths
  blocks {
    title: "AIDS-related deaths"
    description: "Measures the number of people who die from illness related to acquired immunodeficiency syndrome (AIDS), the most advanced stage of HIV infection. Because HIV/AIDS targets the immune system, people typically die from a related illness, like tuberculosis or cancer, rather than from the virus itself. "
    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "HivDeathsPeople"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "AIDS-related deaths (number of people) (${date})"
        stat_var_key: "HivDeathsPeople"
      }
    }
  }

  # People receiving treatment
  blocks {
    title: "Percent of people receiving treatment for HIV"
    description: "Measures the number of people receiving antiretroviral therapy (ART). ART can enable patients to live relatively normal, healthy lives, and avoid transmitting the virus to their child or sexual partners."
    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "HivPeopleLivingWithHIVReceivingARTPercent"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "People living with HIV receiving antiretroviral therapy (percent) (${date})"
        stat_var_key: "HivPeopleLivingWithHIVReceivingARTPercent"
      }
    }
  }

  # Incidence of Malaria
  blocks {
    title: "Incidence of Malaria"
    description: "Malaria is a disease caused by a parasite and spread via mosquitoes. This measures the number of cases per 1,000 people at risk in Africa every year. To reduce malaria infections, world health programs distribute preventive drugs and insecticide-treated bed nets to protect people from mosquito bites."
    columns {
      tiles {
        type: HIGHLIGHT
        description: "in ${placeName}"
        stat_var_key: "sdg/SH_STA_MALR_alternate_unit"
      }
    }
  }
  blocks {
    columns {
      tiles {
        title: "Incidence of malaria in ${placeName} per 1,000 population at risk"
        type: LINE
        stat_var_key: "sdg/SH_STA_MALR"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "Incidence of malaria per 1,000 population at risk (${date})"
        stat_var_key: "sdg/SH_STA_MALR"
      }
    }
  }

  # Incidence of Tuberculosis
  blocks {
    title: "Incidence of Tuberculosis"
    description: "Tuberculosis is a disease caused by germs that are spread from person to person through the air. This measures the number of cases in Africa every year."
    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "sdg/SH_TBS_INCD"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "Incidence of tuberculosis (TB) (${date})"
        stat_var_key: "sdg/SH_TBS_INCD"
      }
    }
  }

  stat_var_spec {
    key: "HivNewInfectionsPeople"
    value {
      stat_var: "HivNewInfectionsPeople"
      name: "New HIV infections (number of people)"
    }
  }

  stat_var_spec {
    key: "HivDeathsPeople"
    value {
      stat_var: "HivDeathsPeople"
      name: "AIDS-related deaths (number of people)"
    }
  }

  stat_var_spec {
    key: "HivPeopleLivingWithHIVReceivingARTPercent"
    value {
      stat_var: "HivPeopleLivingWithHIVReceivingARTPercent"
      name: "People living with HIV receiving antiretroviral therapy (percent)"
    }
  }

  stat_var_spec {
    key: "sdg/SH_STA_MALR"
    value {
      stat_var: "sdg/SH_STA_MALR"
      name: "Incidence of malaria per 1,000 population at risk"
    }
  }

  stat_var_spec {
    key: "sdg/SH_STA_MALR_alternate_unit"
    value {
      stat_var: "sdg/SH_STA_MALR"
      name: "Incidence of malaria per 1,000 population at risk"
      unit: "Cases of Malaria per 1,000 people at risk"
    }
  }

  stat_var_spec {
    key: "sdg/SH_TBS_INCD"
    value {
      stat_var: "sdg/SH_TBS_INCD"
      name: "Incidence of tuberculosis (TB)"
    }
  }

}

### FOOD SECURITY ###
categories {
  title: "Food security and hunger"
  description: "Hunger is the most visible indicator of poverty. Every one of us needs food to stay alive and healthy, and families will almost always prioritise food over other expenses. So when they can’t afford to eat, you know they are in crisis. Hunger is an umbrella term used to mean several different things. This page explores some of the most common measures of hunger and what they mean."

  # Stunting
  blocks {
    title: "Child stunting"
    description: "Stunting means that children are smaller than expected for their age. It is typically a sign of long-term micronutrient deficiency. Stunting often has lifelong consequences because it impacts childrens’ cognitive and physical development. "
    columns {
      tiles {
        type: HIGHLIGHT
        description: "in ${placeName} are moderately or severely stunted"
        stat_var_key: "sdg/SH_STA_STNT.AGE--Y0T4"
      }
    }
  }
  blocks {
    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "sdg/SH_STA_STNT.AGE--Y0T4"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "Proportion of children under 5 years old moderately or severely stunted (${date})"
        stat_var_key: "sdg/SH_STA_STNT.AGE--Y0T4"
      }
    }
  }

  # Wasting
  blocks {
    title: "Child wasting"
    description: "Wasting means that children have a low weight for their height. It is typically a sign of recent and severe weight loss, due to food insecurity or infectious disease."
    columns {
      tiles {
        type: HIGHLIGHT
        description: "in ${placeName} are moderately or severely wasted"
        stat_var_key: "sdg/SH_STA_WAST.AGE--Y0T4"
      }
    }
  }
  blocks {
    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "sdg/SH_STA_WAST.AGE--Y0T4"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "Proportion of children under 5 years old moderately or severely wasted (${date})"
        stat_var_key: "sdg/SH_STA_WAST.AGE--Y0T4"
      }
    }
  }

  # Undernourishment
  blocks {
    title: "Prevalence of undernourishment"
    description: "Someone is undernourished if they are not able to acquire enough food to meet the daily minimum dietary energy requirements, over a period of one year. Undernourishment is a precursor to both stunting and wasting, so increasing rates can flag where food assistance is urgently needed."
    columns {
      tiles {
        type: HIGHLIGHT
        description: "of the population in ${placeName} are undernourished"
        stat_var_key: "sdg/SN_ITK_DEFC"
      }
    }
  }
  blocks {
    columns {
      tiles {
        type: RANKING
        ranking_tile_spec {
          show_highest: true
          show_lowest: true
        }
        stat_var_key: "sdg/SN_ITK_DEFC"
      }
    }
    columns {
      tiles {
        type: MAP
        title: "Prevalence of undernourishment (${date})"
        stat_var_key: "sdg/SN_ITK_DEFC"
      }
    }
  }

  stat_var_spec {
    key: "sdg/SH_STA_STNT.AGE--Y0T4"
    value {
      stat_var: "sdg/SH_STA_STNT.AGE--Y0T4"
      name: "Proportion of children under 5 years old moderately or severely stunted"
    }
  }

  stat_var_spec {
    key: "sdg/SH_STA_WAST.AGE--Y0T4"
    value {
      stat_var: "sdg/SH_STA_WAST.AGE--Y0T4"
      name: "Proportion of children moderately or severely wasted [under 5 years old]"
    }
  }

  stat_var_spec {
    key: "sdg/SN_ITK_DEFC"
    value {
      stat_var: "sdg/SN_ITK_DEFC"
      name: "Prevalence of undernourishment"
    }
  }
}