# This is a Vertex AI model with public endpoint.
us-central1:
  protocol: rest
  endpoint_id: "7109398204734504960"

# Used for testing, this points to the region to use for local testing.
local:
  region: us-central1