# Review settings for Gemini Code Assist in GitHub
# Documentation: https://developers.google.com/gemini-code-assist/docs/customize-gemini-behavior-github#add-configuration-files
have_fun: false
code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  max_review_comments: -1
  pull_request_opened:
    help: false
    summary: true
    code_review: true
    include_drafts: true
ignore_patterns: ["import/**", "mixer/**"]
