# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## This file specifies the topic page config for poverty in USA

metadata {
  topic_id: "dc2_1"
  topic_name: "DC2.1 Dashboard"
  place_dcid: "country/COL"
  contained_place_types {
    key: "State"
    value: "County"
  }
}

categories {
  title: "The Economy"
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ultricies non sem interdum convallis. Ut sed maximus lacus, sit amet dapibus augue. Donec in elit in nunc vulputate volutpat. Donec vestibulum ullamcorper tristique. Cras quis laoreet ante. Duis sodales tellus ut leo facilisis sollicitudin. Cras viverra pulvinar lobortis."

  blocks {
    title: "Gross National Income"
    
      columns {
      tiles {
        type: HIGHLIGHT
        description: "Gross National Income for ${placeName} (${date})"
        stat_var_key: "gni_ppp"
      }
      tiles {
        type: DESCRIPTION
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ultricies non sem interdum convallis. Ut sed maximus lacus, sit amet dapibus augue. Donec in elit in nunc vulputate volutpat. Donec vestibulum ullamcorper tristique. Cras quis laoreet ante. Duis sodales tellus ut leo facilisis sollicitudin. Cras viverra pulvinar lobortis."
      }
    }

    columns {
      tiles {
        type: LINE
        title: "Gross National Income in ${placeName}"
        stat_var_key: "gni_ppp"
      }
    }
  }

  blocks {
    title: "Nominal GDP"
    columns {
      tiles {
        type: LINE
        title: "Nominal GDP in ${placeName}"
        stat_var_key: "nominal_gdp"
      }
    }
  }

  blocks {
    title: "Labor Force"
    columns {
      tiles {
        type: LINE
        title: "Percent of Working Age Population in the Labor Forcee in ${placeName}"
        stat_var_key: "pct_pop_laborforce"
      }
    }
  }

  blocks {
    title: "Income Inequality"
    columns {
      tiles {
        type: LINE
        title: "Gini Index of Economic Activity in ${placeName}"
        stat_var_key: "gini_index_economicactivity"
      }
    }
  }

  stat_var_spec {
    key: "gni_ppp"
    value {
      stat_var: "Amount_EconomicActivity_GrossNationalIncome_PurchasingPowerParity"
      name: "Gross National Income Based on Purchasing Power Parity"
    }
  }

  stat_var_spec {
    key: "nominal_gdp"
    value {
      stat_var: "Amount_EconomicActivity_GrossDomesticProduction_Nominal"
      name: "Nominal GDP"
    }
  }

  stat_var_spec {
    key: "pct_pop_laborforce"
    value {
      stat_var: "Count_Person_15To64Years_InLaborForce_AsFractionOf_Count_Person_15To64Years"
      name: "Percent of Working Age Population in the Labor Force"
    }
  }

  stat_var_spec {
    key: "gini_index_economicactivity"
    value {
      stat_var: "GiniIndex_EconomicActivity"
      name: "Gini Index of Economic Activity of a Population"
    }
  }
}

categories {
  title: "Demographics"
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ultricies non sem interdum convallis. Ut sed maximus lacus, sit amet dapibus augue. Donec in elit in nunc vulputate volutpat. Donec vestibulum ullamcorper tristique. Cras quis laoreet ante. Duis sodales tellus ut leo facilisis sollicitudin. Cras viverra pulvinar lobortis."

  blocks {
    title: "Urban/Rural"
    columns {
      tiles {
        type: LINE
        title: "Population Living in Urban vs. Rural Areas in ${placeName}"
        stat_var_key: "pop_urban"
        stat_var_key: "pop_rural"
      }
    }
  }

  stat_var_spec {
    key: "pop_urban"
    value {
      stat_var: "Count_Person_Urban"
      name: "Population Living in Urban Areas"
    }
  }
  stat_var_spec {
    key: "pop_rural"
    value {
      stat_var: "Count_Person_Rural"
      name: "Population Living in Rural Areas"
    }
  }  

  blocks {
    title: "Poverty"
    columns {
      tiles {
        type: LINE
        title: "Employed population below international poverty line in ${placeName}"
        stat_var_key: "poverty_rate_15_24"
        stat_var_key: "poverty_rate_15_older"
        stat_var_key: "poverty_rate_25_older"
      }
    }
  }

  stat_var_spec {
    key: "pop_urban"
    value {
      stat_var: "Count_Person_Urban"
      name: "Population Living in Urban Areas"
    }
  }
  stat_var_spec {
    key: "pop_rural"
    value {
      stat_var: "Count_Person_Rural"
      name: "Population Living in Rural Areas"
    }
  }  
  stat_var_spec {
    key: "poverty_rate_15_24"
    value {
      stat_var: "sdg/SI_POV_EMP1_15-24"
      name: "Employed population below international poverty line: 15 to 24 years old"
    }
  }  
  stat_var_spec {
    key: "poverty_rate_15_older"
    value {
      stat_var: "sdg/SI_POV_EMP1_15GEQ"
      name: "Employed population below international poverty line: 15 years old and over"
    }
  }  
  stat_var_spec {
    key: "poverty_rate_25_older"
    value {
      stat_var: "sdg/SI_POV_EMP1_25GEQ"
      name: "Employed population below international poverty line: 25 years old and over"
    }
  }  
}


categories {
  title: "Crime"
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ultricies non sem interdum convallis. Ut sed maximus lacus, sit amet dapibus augue. Donec in elit in nunc vulputate volutpat. Donec vestibulum ullamcorper tristique. Cras quis laoreet ante. Duis sodales tellus ut leo facilisis sollicitudin. Cras viverra pulvinar lobortis."

  blocks {
    title: "Murder and Non Negligent Manslaughter"
    columns {
      tiles {
        type: LINE
        title: "Murder and Non Negligent Manslaughter Cases Per Capita in ${placeName}"
        stat_var_key: "murder_pc"
        stat_var_key: "murder_pc_male"
        stat_var_key: "murder_pc_female"
      }
    }
  }

  stat_var_spec {
    key: "murder_pc"
    value {
      stat_var: "Count_CriminalActivities_MurderAndNonNegligentManslaughter_AsFractionOf_Count_Person"
      name: "Murder and Non Negligent Manslaughter Cases Per Capita"
    }
  }
  stat_var_spec {
    key: "murder_pc_male"
    value {
      stat_var: "Count_CriminalActivities_MurderAndNonNegligentManslaughter_Male_AsFractionOf_Count_Person_Male"
      name: "Murder and Non Negligent Manslaughter Cases Per Capita for the Male Population"
    }
  }
  stat_var_spec {
    key: "murder_pc_female"
    value {
      stat_var: "Count_CriminalActivities_MurderAndNonNegligentManslaughter_Female_AsFractionOf_Count_Person_Female"
      name: "Murder and Non Negligent Manslaughter Cases Per Capita for the Female Population"
    }
  }
}

categories {
  title: "Health"
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ultricies non sem interdum convallis. Ut sed maximus lacus, sit amet dapibus augue. Donec in elit in nunc vulputate volutpat. Donec vestibulum ullamcorper tristique. Cras quis laoreet ante. Duis sodales tellus ut leo facilisis sollicitudin. Cras viverra pulvinar lobortis."

  blocks {
    title: "Infant Mortality"
    columns {
      tiles {
        type: LINE
        title: "Infant Mortality Rate in ${placeName}"
        stat_var_key: "infant_mortality"
      }
    }
  }

  stat_var_spec {
    key: "infant_mortality"
    value {
      stat_var: "Count_Death_0Years_AsFractionOf_Count_BirthEvent_LiveBirth"
      name: "Infant Mortality Rate"
    }
  }

}


categories {
  title: "Education"
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ultricies non sem interdum convallis. Ut sed maximus lacus, sit amet dapibus augue. Donec in elit in nunc vulputate volutpat. Donec vestibulum ullamcorper tristique. Cras quis laoreet ante. Duis sodales tellus ut leo facilisis sollicitudin. Cras viverra pulvinar lobortis."

  blocks {
    title: "Completion rate: Upper secondary"
    columns {
      tiles {
        type: LINE
        title: "Completion rate: Upper secondary in ${placeName}"
        stat_var_key: "upper_secondary_pc"
      }
    }
  }

  blocks {
    title: "Bachelors Degree or Higher"
    columns {
      tiles {
        type: LINE
        title: "Bachelors Degree or Higher in ${placeName}"
        stat_var_key: "bachelors_pc"
        stat_var_key: "bachelors_pc_male"
        stat_var_key: "bachelors_pc_female"
      }
    }
  }

  stat_var_spec {
    key: "bachelors_pc"
    value {
      stat_var: "Count_Person_25OrMoreYears_BachelorsDegreeOrHigher_AsFractionOf_Count_Person_25OrMoreYears"
      name: "Population: Bachelors Degree or Higher (As Fraction of Count Person 25 or More Years)"
    }
  }
  stat_var_spec {
    key: "bachelors_pc_male"
    value {
      stat_var: "Count_Person_25OrMoreYears_Female_BachelorsDegreeOrHigher_AsFractionOf_Count_Person_25OrMoreYears_Female"
      name: "Population: Bachelors Degree or Higher, Male (As Fraction of Count Person 25 or More Years Male)"
    }
  }
  stat_var_spec {
    key: "bachelors_pc_female"
    value {
      stat_var: "Count_Person_25OrMoreYears_Male_BachelorsDegreeOrHigher_AsFractionOf_Count_Person_25OrMoreYears_Male"
      name: "Population: Bachelors Degree or Higher, Female (As Fraction of Count Person 25 or More Years Female)"
    }
  }
  stat_var_spec {
    key: "upper_secondary_pc"
    value {
      stat_var: "sdg/SE_TOT_CPLR_UPPSEC"
      name: "Completion rate: Upper secondary"
    }
  }
}

categories {
  title: "Access to Basic Services"
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ultricies non sem interdum convallis. Ut sed maximus lacus, sit amet dapibus augue. Donec in elit in nunc vulputate volutpat. Donec vestibulum ullamcorper tristique. Cras quis laoreet ante. Duis sodales tellus ut leo facilisis sollicitudin. Cras viverra pulvinar lobortis."

  blocks {
    title: "Proportion of population using basic drinking water services"
    columns {
      tiles {
        type: LINE
        title: "Proportion of population using basic drinking water services in ${placeName}"
        stat_var_key: "basic_water_services_pc"
      }
    }
  }

  stat_var_spec {
    key: "basic_water_services_pc"
    value {
      stat_var: "sdg/SP_ACS_BSRVH2O"
      name: "Proportion of population using basic drinking water services"
    }
  }

}
