# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## Test topic page for asia

metadata {
  topic_id: "test-asia"
  topic_name: "Test for tile spec"
  place_dcid: "asia"
  contained_place_types {
    key: "Continent"
    value: "Country"
  }
}

categories {
  title: "Testing geoJsonProp, placeNameProp, subtitle"
  blocks {
    columns {
      tiles {
        type: MAP
        title: "GDP (Nominal Value) (${date})"
        subtitle: "Countries"
        stat_var_key: "Amount_EconomicActivity_GrossDomesticProduction_Nominal"
        place_name_prop: "unDataLabel"
        map_tile_spec {
          geo_json_prop: "geoJsonCoordinatesUN"
        }
      }
    }
  }
  blocks: {
    columns {
      tiles {
        type: BAR
        title: "GDP (Nominal Value) (${date})"
        subtitle: "Countries"
        stat_var_key: "Amount_EconomicActivity_GrossDomesticProduction_Nominal"
        place_name_prop: "unDataLabel"
        bar_tile_spec: {
          variable_name_regex: "(?<=GDP).*"
          default_variable_name: "Should not show"
        }
      }
    }
    columns {
      tiles {
        type: BAR
        title: "GDP (Nominal Value) (${date})"
        subtitle: "Countries"
        stat_var_key: "worldBank/NE_EXP_GNFS_CD"
        place_name_prop: "unDataLabel"
        bar_tile_spec: {
          variable_name_regex: "(?<=GDP).*"
          default_variable_name: "Exports"
        }
      }
    }
    columns {
      tiles {
        type: SCATTER
        title: "Population vs GDP"
        subtitle: "Countries"
        stat_var_key: "Count_Person"
        stat_var_key: "Amount_EconomicActivity_GrossDomesticProduction_Nominal"
        place_name_prop: "unDataLabel"
      }
    }
  }
  stat_var_spec {
    key: "Amount_EconomicActivity_GrossDomesticProduction_Nominal"
    value {
      stat_var: "Amount_EconomicActivity_GrossDomesticProduction_Nominal"
      name: "GDP Total"
    }
  }
  stat_var_spec {
    key: "worldBank/NE_EXP_GNFS_CD"
    value {
      stat_var: "worldBank/NE_EXP_GNFS_CD"
      name: "Exports of goods and services (current US$)"
    }
  }
  stat_var_spec {
    key: "Amount_EconomicActivity_GrossDomesticProduction_Nominal_PerCapita"
    value {
      stat_var: "Amount_EconomicActivity_GrossDomesticProduction_Nominal_PerCapita"
      name: "GDP Per Capita"
    }
  }
  stat_var_spec {
    key: "Count_Person"
    value {
      stat_var: "Count_Person"
      name: "Population"
    }
  }
}
