# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: id_map.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='id_map.proto',
  package='datacommons.proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0cid_map.proto\x12\x11\x64\x61tacommons.proto\"7\n\x07\x44\x63idMid\x12\x0c\n\x04\x64\x63id\x18\x01 \x01(\t\x12\x0b\n\x03mid\x18\x02 \x03(\t\x12\x11\n\tprov_hrid\x18\x03 \x01(\t\"\xca\x01\n\nDcidMidMap\x12(\n\x04type\x18\x01 \x03(\x0b\x32\x1a.datacommons.proto.DcidMid\x12(\n\x04prop\x18\x02 \x03(\x0b\x32\x1a.datacommons.proto.DcidMid\x12\x35\n\x07val_set\x18\x03 \x03(\x0b\x32$.datacommons.proto.DcidMidMap.ValSet\x1a\x31\n\x06ValSet\x12\'\n\x03val\x18\x02 \x03(\x0b\x32\x1a.datacommons.proto.DcidMid')
)




_DCIDMID = _descriptor.Descriptor(
  name='DcidMid',
  full_name='datacommons.proto.DcidMid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dcid', full_name='datacommons.proto.DcidMid.dcid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mid', full_name='datacommons.proto.DcidMid.mid', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prov_hrid', full_name='datacommons.proto.DcidMid.prov_hrid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=90,
)


_DCIDMIDMAP_VALSET = _descriptor.Descriptor(
  name='ValSet',
  full_name='datacommons.proto.DcidMidMap.ValSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='datacommons.proto.DcidMidMap.ValSet.val', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=295,
)

_DCIDMIDMAP = _descriptor.Descriptor(
  name='DcidMidMap',
  full_name='datacommons.proto.DcidMidMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='datacommons.proto.DcidMidMap.type', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prop', full_name='datacommons.proto.DcidMidMap.prop', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val_set', full_name='datacommons.proto.DcidMidMap.val_set', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DCIDMIDMAP_VALSET, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=295,
)

_DCIDMIDMAP_VALSET.fields_by_name['val'].message_type = _DCIDMID
_DCIDMIDMAP_VALSET.containing_type = _DCIDMIDMAP
_DCIDMIDMAP.fields_by_name['type'].message_type = _DCIDMID
_DCIDMIDMAP.fields_by_name['prop'].message_type = _DCIDMID
_DCIDMIDMAP.fields_by_name['val_set'].message_type = _DCIDMIDMAP_VALSET
DESCRIPTOR.message_types_by_name['DcidMid'] = _DCIDMID
DESCRIPTOR.message_types_by_name['DcidMidMap'] = _DCIDMIDMAP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DcidMid = _reflection.GeneratedProtocolMessageType('DcidMid', (_message.Message,), dict(
  DESCRIPTOR = _DCIDMID,
  __module__ = 'id_map_pb2'
  # @@protoc_insertion_point(class_scope:datacommons.proto.DcidMid)
  ))
_sym_db.RegisterMessage(DcidMid)

DcidMidMap = _reflection.GeneratedProtocolMessageType('DcidMidMap', (_message.Message,), dict(

  ValSet = _reflection.GeneratedProtocolMessageType('ValSet', (_message.Message,), dict(
    DESCRIPTOR = _DCIDMIDMAP_VALSET,
    __module__ = 'id_map_pb2'
    # @@protoc_insertion_point(class_scope:datacommons.proto.DcidMidMap.ValSet)
    ))
  ,
  DESCRIPTOR = _DCIDMIDMAP,
  __module__ = 'id_map_pb2'
  # @@protoc_insertion_point(class_scope:datacommons.proto.DcidMidMap)
  ))
_sym_db.RegisterMessage(DcidMidMap)
_sym_db.RegisterMessage(DcidMidMap.ValSet)


# @@protoc_insertion_point(module_scope)
