spec: {
  pop_type: "EconomicActivity"
  vertical: "Economics"
  cprop: "activitySource"
  obs_props: {
     mprop: "amount"
     stat_type: "growthRate"
     name: "Growth Rate"
  }
  obs_props:{
    mprop: "amount"
    stat_type: "measuredValue"
    mqual: "Nominal"
    name: "Nominal"
  }
  obs_props:{
    mprop: "amount"
    stat_type: "measuredValue"
    mqual: "RealValue"
    name: "Real value"
  }

  obs_props:{
    mprop: "amount"
    stat_type: "measuredValue"
    mqual: "Nominal"
    mdenom: "PerCapita"
    name: "Nominal Per Capita"
  }

  obs_props:{
    mprop: "amount"
    stat_type: "measuredValue"
    mqual: "PurchasingPowerParity"
    name: "Purchasing Power Parity"
  }

  obs_props:{
    mprop: "amount"
    stat_type: "measuredValue"
    mqual: "PurchasingPowerParity"
    mdenom: "PerCapita"
    name: "Purchasing Power Parity Per Capita"
  }
}