# Whitelist of PopType, Mprop, Cprops that have intents defined in search.
# This file is used by GNI tool, and essentially (ab)uses PopObsSpec.
#
# The full aspirational list is here: https://docs.google.com/spreadsheets/d/1qzA86AjagH6nmom79dxcXJmIoJ3PA4uX6GrgpgYYlqU/

spec: {
  pop_type: "Person"
  mprop: "count"

  # Demographics
  cprop: "gender"
  cprop: "race"
  cprop: "povertyStatus"
  cprop: "maritalStatus"
  cprop: "educationalAttainment"
  cprop: "employment"
  cprop: "age"
  cprop: "income"
  cprop: "healthInsurance"
  cprop: "detailedLevelOfSchool"
}

spec: {
  pop_type: "Person"
  mprop: "age"
  cprop: "gender"
  cprop: "race"
}

spec: {
  pop_type: "Person"
  mprop: "income"
  cprop: "gender"
  cprop: "educationalAttainment"
}

spec: {
  pop_type: "Person"
  mprop: "percent"

  # Health
  cprop: "healthBehavior"
  cprop: "healthOutcome"
  cprop: "healthPrevention"
  cprop: "gender"
}

spec: {
  pop_type: "CriminalActivities"
  mprop: "count"
  cprop: "crimeType"
}

spec: {
  pop_type: "MortalityEvent"
  mprop: "count"
  cprop: "gender"
  cprop: "race"
  cprop: "causeOfDeath"
  cprop: "age"
}

spec: {
  pop_type: "BLSEstablishment"
  mprop: "count"
  cprop: "naics"
}

spec: {
  pop_type: "BLSWorker"
  mprop: "count"
  cprop: "naics"
}

spec: {
  pop_type: "Household"
  mprop: "count"
  cprop: "householderAge"
  cprop: "householderRace"
  cprop: "income"
}

spec: {
  pop_type: "HousingUnit"
  mprop: "count"
  cprop: "occupancyStatus"
  cprop: "numberOfRooms"
  cprop: "grossRent"
  cprop: "homeValue"
}

spec: {
  pop_type: "CycloneEvent"
  mprop: "count"
}
spec: {
  pop_type: "DroughtEvent"
  mprop: "count"
}
spec: {
  pop_type: "EarthquakeEvent"
  mprop: "count"
}
spec: {
  pop_type: "FloodEvent"
  mprop: "count"
}
spec: {
  pop_type: "ThunderstormWindEvent"
  mprop: "count"
}
spec: {
  pop_type: "TornadoEvent"
  mprop: "count"
}
spec: {
  pop_type: "WildlandFireEvent"
  mprop: "count"
}