# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stat_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stat_config.proto',
  package='datacommons.proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x11stat_config.proto\x12\x11\x64\x61tacommons.proto\"\xbf\x01\n\nPopObsSpec\x12\x10\n\x08pop_type\x18\x01 \x01(\t\x12\r\n\x05mprop\x18\x02 \x01(\t\x12\x11\n\tstat_type\x18\x03 \x01(\t\x12\r\n\x05\x63prop\x18\x04 \x03(\t\x12-\n\x03\x64pv\x18\x05 \x03(\x0b\x32 .datacommons.proto.PopObsSpec.PV\x12\x0c\n\x04name\x18\x06 \x01(\t\x12\x10\n\x08vertical\x18\x07 \x03(\t\x1a\x1f\n\x02PV\x12\x0c\n\x04prop\x18\x01 \x01(\t\x12\x0b\n\x03val\x18\x02 \x01(\t\"=\n\x0ePopObsSpecList\x12+\n\x04spec\x18\x01 \x03(\x0b\x32\x1d.datacommons.proto.PopObsSpec')
)




_POPOBSSPEC_PV = _descriptor.Descriptor(
  name='PV',
  full_name='datacommons.proto.PopObsSpec.PV',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prop', full_name='datacommons.proto.PopObsSpec.PV.prop', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val', full_name='datacommons.proto.PopObsSpec.PV.val', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=232,
)

_POPOBSSPEC = _descriptor.Descriptor(
  name='PopObsSpec',
  full_name='datacommons.proto.PopObsSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pop_type', full_name='datacommons.proto.PopObsSpec.pop_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mprop', full_name='datacommons.proto.PopObsSpec.mprop', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stat_type', full_name='datacommons.proto.PopObsSpec.stat_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cprop', full_name='datacommons.proto.PopObsSpec.cprop', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dpv', full_name='datacommons.proto.PopObsSpec.dpv', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='datacommons.proto.PopObsSpec.name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vertical', full_name='datacommons.proto.PopObsSpec.vertical', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_POPOBSSPEC_PV, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=232,
)


_POPOBSSPECLIST = _descriptor.Descriptor(
  name='PopObsSpecList',
  full_name='datacommons.proto.PopObsSpecList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spec', full_name='datacommons.proto.PopObsSpecList.spec', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=295,
)

_POPOBSSPEC_PV.containing_type = _POPOBSSPEC
_POPOBSSPEC.fields_by_name['dpv'].message_type = _POPOBSSPEC_PV
_POPOBSSPECLIST.fields_by_name['spec'].message_type = _POPOBSSPEC
DESCRIPTOR.message_types_by_name['PopObsSpec'] = _POPOBSSPEC
DESCRIPTOR.message_types_by_name['PopObsSpecList'] = _POPOBSSPECLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PopObsSpec = _reflection.GeneratedProtocolMessageType('PopObsSpec', (_message.Message,), dict(

  PV = _reflection.GeneratedProtocolMessageType('PV', (_message.Message,), dict(
    DESCRIPTOR = _POPOBSSPEC_PV,
    __module__ = 'stat_config_pb2'
    # @@protoc_insertion_point(class_scope:datacommons.proto.PopObsSpec.PV)
    ))
  ,
  DESCRIPTOR = _POPOBSSPEC,
  __module__ = 'stat_config_pb2'
  # @@protoc_insertion_point(class_scope:datacommons.proto.PopObsSpec)
  ))
_sym_db.RegisterMessage(PopObsSpec)
_sym_db.RegisterMessage(PopObsSpec.PV)

PopObsSpecList = _reflection.GeneratedProtocolMessageType('PopObsSpecList', (_message.Message,), dict(
  DESCRIPTOR = _POPOBSSPECLIST,
  __module__ = 'stat_config_pb2'
  # @@protoc_insertion_point(class_scope:datacommons.proto.PopObsSpecList)
  ))
_sym_db.RegisterMessage(PopObsSpecList)


# @@protoc_insertion_point(module_scope)